### PR TITLE
Fix OOM lakectl FS upload bug

### LINKED ISSUE #8088: [Bug]: lakectl fs upload Causes OOM Error During Large File Uploads
### What happened?

`lakectl fs upload` command causes an Out-Of-Memory (OOM) error, resulting in the process being killed by the kernel or freezing the OS during the upload of large files. 

**Environment:**

- Memory: 16GB
- Storage: Local system with multiple folders, each ~200GB, hosted locally.
- Repository: Google Cloud Storage (GCS)

Steps to Reproduce:

 - Attempt to upload a large directory with multiple small files using lakectl fs upload:
```lakectl fs upload --source . --recursive "lakefs://${LAKEFS_REPO_NAME}/${DEFAULT_BRANCH}/" --pre-sign -p 8 ```
Reducing p doesn't solve the issue
- Observe that the system either encounters an OOM error or freezes.

### Expected behavior

File uploaded successfully 

### lakeFS version

1.31.1

### How lakeFS is installed

GCP

### Affected clients

All

### Relevant log output

```shell
22352 Killed lakectl fs upload --source . --recursive "lakefs://${LAKEFS_REPO_NAME}/${DEFAULT_BRANCH}/" --pre-sign -p 8
```

### Contact details

_No response_

### PR DESCRIPTION
**Pull request by idanovo**
Closes #8088

### CODE REVIEW

**Review by itaiad200 — COMMENTED** [review]
Could you explain how this PR solves the linked issue?

**Comment by idanovo** [comment]
@itaiad200 Yes, follow me-

From the uploadObject/UploadPartObject we have this code:

```
	req, err := http.NewRequestWithContext(ctx, http.MethodPut, preSignURL, body)
        ...
	putResp, err := u.uploader.HTTPClient.Do(req)
```
the type of the body we pass to NewRequestWithContext is local.fileWrapper which implement seek but doesn't implement close
so the http.NewRequestFromContext function get to this code:
```
	rc, ok := body.(io.ReadCloser)
	if !ok && body != nil {
		rc = io.NopCloser(body)
	}
```
So we get a request from body that implements close (NopCloser) but doesn't implement seek

Now when getting to this line- putResp, err := u.uploader.HTTPClient.Do(req)
If our HTTP client is the retryable client the Do function will eventually get to this code:
```
	case io.ReadSeeker:
         ...
	// Read all in so we can reset
	case io.Reader:
		buf, err := io.ReadAll(body)
```
Now, because our body doesn't implement seek but does implement read, we will call io.ReadAll and read the entire file into the memory and crush.

**Review by Isan-Rivkin — APPROVED** [review]
NICE Research! 
Sometimes small solutions solve big problems :)

**Review by itaiad200 — APPROVED** [review]
Thanks for the clear explanation. How was this tested?

**Comment by idanovo** [comment]
> Thanks for the clear explanation. How was this tested?

@itaiad200 I built a docker image that runs lakectl fs upload and tries to upload a 1GB file using the --memory=2048m flag.
First I saw that the bug reproduced when running it using the master branch, and then tested that my code made it work.

**Review by arielshaqed — APPROVED** [review]
Wow, best!

**Comment by arielshaqed** [comment]
https://imgflip.com/i/99kzey
Corgi meme: Wow / much memory / very progress / close() / very fix

**Pull request merged**
