### PR TITLE
Add a test for ApiClient.translateURI

### LINKED ISSUE #4079: Add a test for ApiClient.translateURI

### PR DESCRIPTION
**Pull request by arielshaqed**
By changing "ignore" to "it" you can exercise #4072.

Fixes #4079.

### CODE REVIEW

**Comment by arielshaqed** [comment]
Now rebased on #4072 (submitted), and indeed un-ignored and working.

**Comment by arielshaqed** [comment]
Ping @lynnro314 ...

**Review by talSofer — APPROVED** [review]
LGTM, thanks!

**Comment by arielshaqed** [comment]
Thanks!

**Pull request merged**
