### PR TITLE
Fix lakectl upload with pre-sign for Azure

### PR DESCRIPTION
**Pull request by guy-har**

### CODE REVIEW

**Review by N-o-Z — CHANGES_REQUESTED** [review]
The code looks good though I do have 2 questions:
1. How does this resolve https://github.com/treeverse/lakeFS/issues/6643 (which was already closed by another PR)
2. Can we add tests that cover this scenario

**Comment by nopcoder** [comment]
Removing myself as @N-o-Z already on it.

**Comment by guy-har** [comment]
@N-o-Z Changed the connected issue and added tests as requested. The tests required a few more changes, and I opened the following issues as part of it
#6743 #6744 #6745 
PTAL

**Comment by guy-har** [comment]
> @guy-har Thanks - can you please link / open the correct issue for this PR?
@N-o-Z what's wrong with the current issue? (#6426 )

**Pull request merged**
