### PR TITLE
Split treeverse/lakefs into 2 images, without duckdb by default

### LINKED ISSUE #5836: Split DuckDB out of main lakeFS Docker image
Place DuckDB in a separate Docker image treeverse/lakefs-duckdb and remove
it from the main Docker image treeverse/lakefs.

Having DuckDB in the lakeFS Docker image is a poor experience for running
lakeFS in production:

* lakeFS _does not require DuckDB_ at any stage
* Complex supply chain
* We need to track releases of DuckDB
  * Fix potentially-vulnerable lakeFS images
  * Our largest _production users_ may need to track _our_ images for
    vulnerabilities in a product they do not use
* Less composable
* Non-minimal interface created on image
* Not SOA in general and microservices in particular
* More complex licensing for our users
...

This was recently introduced in [#5787 for reasons of speed and
agility](https://github.com/treeverse/lakeFS/pull/5787#issuecomment-1539960668),
so we should get rid of it as quickly as possible before anyone actually
relies on it: [Hyrum's Law](https://www.hyrumslaw.com/) and [XKCD
1172](https://xkcd.com/1172/) both apply.

### PR DESCRIPTION
**Pull request by arielshaqed**
* treeverse/lakefs will *not* include duckdb
* treeverse/lakefs-with-duckdb *will* include duckdb

Fixes #5836.

Tested _manually_ by examining the images treeverse/lakefs and
treeverse/lakefs-with-duckdb after `make build-docker`.

Releasing with this PR will push treeverse/lakefs to Docker Hub, and we can
push treeverse/lakefs-with-duckdb there manually.  We will automate this
later.

### CODE REVIEW

**Comment by arielshaqed** [comment]
Suggested changelog:

> Add treeverse/lakefs-with-duckdb Docker image, published manually.

**Comment by arielshaqed** [comment]
@nopcoder, @itaiad200: I will pull if _either_ of you approves.  I only
added both of you for speed of review.

**Review by nopcoder — CHANGES_REQUESTED** [review]
Thanks Ariel!

Issue and suggestion for this PR:
- The final target `lakefs-lakectl` should be `lakefs-plugins` as it was that the last layer so far.
- We can use the same repository and add variant based on tags. Similar to other image publishing. Ex: treeverse/lakefs:0.100.0 and treeverse/lakefs:0.100.0-duckdb

Not related to this PR:
- we are build latest version of ducket db (main). if it will break it will build our build too.
- we should split the image build to different dockerfile as I don't think we would like to release duckdb as part of lakefs. I'm sure there are other images to run duckdb and it makes are build processes a lot longer.

**Comment by arielshaqed** [comment]
THANKS, PTAL.

> Thanks Ariel!
> 
> Issue and suggestion for this PR:
> 
>     * The final target `lakefs-lakectl` should be `lakefs-plugins` as it was that the last layer so far.

Fixed this bug..

> 
>     * We can use the same repository and add variant based on tags. Similar to other image publishing. Ex: treeverse/lakefs:0.100.0 and treeverse/lakefs:0.100.0-duckdb

... and did this.


> Not related to this PR:
> 
>     * we are build latest version of ducket db (main). if it will break it will build our build too.
> 
>     * we should split the image build to different dockerfile as I don't think we would like to release duckdb as part of lakefs. I'm sure there are other images to run duckdb and it makes are build processes a lot longer.

I agree with both of these.  This PR keeps that behaviour introduced in #5787 for speed and agility - there is not enough documentation to discover what doing this will break, so I am keeping it.

**Comment by rmoff** [comment]
Thanks for doing this @arielshaqed. I'll update the quickstart. One QQ - if we use the tag approach, does that mean we hardcode the version that's used in quickstart? i.e. it'll be

`docker run treeverse/lakefs:0.100.0-duckdb` 

and not 

`docker run treeverse/lakefs-with-duckdb:latest`

so each release of lakeFS will need the quickstart updating? This is fine for now (speed and agilty, right 😉) but just want to check my understanding.

**Comment by arielshaqed** [comment]
> Thanks for doing this @arielshaqed. I'll update the quickstart. One QQ - if we use the tag approach, does that mean we hardcode the version that's used in quickstart? i.e. it'll be
> 
> `docker run treeverse/lakefs:0.100.0-duckdb`
> 
> and not
> 
> `docker run treeverse/lakefs-with-duckdb:latest`
> 
> so each release of lakeFS will need the quickstart updating? This is fine for now (speed and agilty, right wink) but just want to check my understanding.

Indeed.  But a good recommendation is _never_ to use tag `latest`, e.g. [this ancient post](https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375).

**Comment by rmoff** [comment]
@arielshaqed I've set up https://github.com/treeverse/lakeFS/pull/5845 to update the Docker tag - lmk if you are happy to merge into this branch

**Comment by rmoff** [comment]
Also #5847 which fixes the issue that @nopcoder pointed out: 

> we are build latest version of ducket db (main). if it will break it will build our build too.

**Review by nopcoder — APPROVED** [review]
Thanks - LGTM!

**Comment by arielshaqed** [comment]
Rerunning unrelated failing test -- because we're going for a v0.100.0 release, and I'd need to rerun it anyway to ensure it is indeed unrelated 🤷🏽

**Pull request merged**
