### PR TITLE
Fix Swagger Anchor links

### LINKED ISSUE #5940: Docs: Swagger reference is not deep-link-able
trying to deep link to a specific API endpoint in the Swagger documentation loads the page but does not scroll to the relevant position.

### PR DESCRIPTION
**Pull request by rmoff**
- Fix integrity value, add SRI to CSS, bump Swagger UI version
- Add a workaround to make scrolling work

 

### Linked Issue

Closes #5940

---

### Background

See #5940 for full details. tl;dr anchor links within the Swagger page don't work (they don't scroll to where they should)

### Bug Fix

Add a bit of JS to parse the page's URL for an anchor, find that in the DOM, and scroll to it (taking into account the header height)
      

### Testing Details

Tested manually

### CODE REVIEW

**Review by ozkatz — APPROVED** [review]
Thanks! Hope that solves it.

**Review by nopcoder — COMMENTED** [review]
Can give an example of such deep link?
Don't like endless timeout function to fix these issues - I wonder if we can leverage onComplete event to fix it.

**Review by nopcoder — COMMENTED** [review]
Can give an example of such deep link?
Don't like endless timeout function to fix these issues - I wonder if we can leverage onComplete event to fix it.

**Comment by nopcoder** [comment]
Thanks. Suggest to perform the lookup once inside the onComplete callback 
let me know if you need help.

**Comment by nopcoder** [comment]
@rmoff this is what I've hacked that worked for me (I was using the latest swagger ui bundle):

```js
        onComplete: function() {
            const elemId = window.location.hash.replaceAll('!/', '').replaceAll('/', '-').replaceAll('#', '');
            const elem = elemId && document.getElementById('operations' + elemId);
            if (elem) {
                elem.scrollIntoView();
            }
        }
```

**Comment by nopcoder** [comment]
Closing this one a new fix pr with updated code will address the issue.

**Pull request closed without merging**
