### PR TITLE
Added notes that Authentication and Authorization are deprecated

### LINKED ISSUE #5073: It is unclear from the docs that authorization and authentication are deprecated
In the CHANGELOG we indicated authorization and authentication are deprecated, however - it is still not clear from the documentation, or that there is an alternative in case someone needs it.

### PR DESCRIPTION
**Pull request by iddoavn**
FIX #5073 

Added notes that Authentication and Authorization are deprecated and that there is an alternative.

### CODE REVIEW

**Comment by arielshaqed** [comment]
@ortz ?

**Comment by ortz** [comment]
@iddoavn this is not the case, we'll still have authentication and authorization.
SSO in particular is getting deprecated and RABAC.
But, we'll still have basic authentication and ACLs for authorization.
@arielshaqed thanks for the heads up

**Comment by ozkatz** [comment]
Updated. @ortz if this is accurate, please merge :)

**Review by ozkatz — APPROVED** [review]

**Comment by ortz** [comment]
@ozkatz 🙏

**Pull request merged**
