### PR TITLE
Pass cataloger type env var

### PR DESCRIPTION
**Pull request by itaiad200**

### CODE REVIEW

**Review by nopcoder — APPROVED** [review]

**Comment by nopcoder** [comment]
although it will be the default soon...

**Comment by itaiad200** [comment]
Validated - committed data is stored in s3 for rocks cataloger and not for mvcc.

This cannot pass until #1334  is merged.

**Comment by itaiad200** [comment]
> although it will be the default soon...

Yap but then mvcc will run as rocks.

**Comment by nopcoder** [comment]
Applied part of PR #1338

**Pull request closed without merging**
