### PR TITLE
Document how to assume role in the Spark metadata client

### PR DESCRIPTION
**Pull request by arielshaqed**
Also reformat its documentation options, fix paths for 0.1.7, and add a mention of newly-added Hadoop 3 support in Spark 3.1.2+.

### CODE REVIEW

**Comment by arielshaqed** [comment]
## Tips for reviewing

The `<div>`s structure per-version boxes on the page, but GitHub cannot show them in this PR.  However if you pull the branch to your machine, you may see them with the help of `make docs-serve`.

**Review by johnnyaug — APPROVED** [review]
Thank you!!

**Comment by arielshaqed** [comment]
Thanks!

**Comment by arielshaqed** [comment]
I published 0.1.7, it will show up on Maven Central shortly.

**Pull request merged**
