### PR TITLE
Change API event_type from enum to string

### LINKED ISSUE #4608: API's actions' event_type is too narrow
We have more events types than the ones listed here:
https://github.com/treeverse/lakeFS/blob/d3f0438a42f50c81e87052db5932ea3f56a0c77c/api/swagger.yml#L866

The generated clients may fail parsing the response. The python client fails for sure, haven't checked the Java / golang ones.

### PR DESCRIPTION
**Pull request by itaiad200**
closes #4608

### CODE REVIEW

**Comment by N-o-Z** [comment]
@itaiad200  Did you test the fix on a previously unsupported hook?

**Comment by itaiad200** [comment]
> @itaiad200 Did you test the fix on a previously unsupported hook?

Testing it as we speak

**Comment by itaiad200** [comment]
> > @itaiad200 Did you test the fix on a previously unsupported hook?
> 
> Testing it as we speak

Tested locally with `post-commit` and it worked as expected.

**Review by N-o-Z — APPROVED** [review]
Thanks!

**Pull request merged**
