### PR TITLE
4278 add cicd for data use case in docs

### LINKED ISSUE #4278: Add ci/cd for data use case in docs
- Docs need to be updated with CI/CD for data use case with hooks.
- Reference the lakeFS-samples demo notebook 
- Add walkthrough video

### PR DESCRIPTION
**Pull request by vinodhini8694**
Fix #4278

### CODE REVIEW

**Comment by kesarwam** [comment]
@vinodhini8694 Should "Implementing CI/CD pipeline with lakeFS" section be exactly same as "Get started with your first lakeFS webhook" section in Hooks page so you don't have to repeat the instructions that you have on lakeFS samples notebook Readme page?

**Comment by vinodhini8694** [comment]
@kesarwam Under docs/setup/hooks, we are not getting into a specific event-triggered or a use-case. So I simply redirect them to lakeFS-hooks and lakeFS-samples repo to explore more.

In docs/use-cases/cicd-for-datalake, we wanted to cover a specific use case (and in turn a specific pre-merge hook to accomplish that), so included the steps to get the pre-merge hook up and running. That is, everything you need to implement a CI CD for data lake is covered in this use case page and minimized redirects. Wdyt?

**Comment by johnnyaug** [comment]
I think we should wait with this until the reorganization - currently there is already a [page covering this topic](https://docs.lakefs.io/data_lifecycle_management/ci.html)

**Review by adipolak — APPROVED** [review]
LGTM

**Pull request merged**
