### PR TITLE
UGC custom jar for cloud testing

### PR DESCRIPTION
**Pull request by eden-ohana**

### CODE REVIEW

**Comment by nopcoder** [comment]
Hope we can trust our `if` statements.
If we like to be sure we have two separate jobs that one can only mark - we can add another main entry point and refactor the code.

**Review by nopcoder — CHANGES_REQUESTED** [review]
would refactor the code to enable different entry point and reuse the code for this entry point.

**Comment by eden-ohana** [comment]
@nopcoder It's not only the if statement, I removed the code that can delete objects.
I'm not sure I understand what you are suggesting.

**Comment by nopcoder** [comment]
@eden-ohana all the deleted code is inside a scope that runs when sweep is true. The value of sweep is controlled by a configuration. 
So why do we need this change?

**Comment by eden-ohana** [comment]
> @eden-ohana all the deleted code is inside a scope that runs when sweep is true. The value of sweep is controlled by a configuration. So why do we need this change?

for safety, even if somehow wrong configuration is passed, we still won't delete anything.

**Pull request closed without merging**
