### PR TITLE
Fix test secondary iterator

### PR DESCRIPTION
**Pull request by nopcoder**
Fix secondary index iterator test to use the right proto messages for test data and checking the iterator functionality.

### CODE REVIEW

**Review by N-o-Z — CHANGES_REQUESTED** [review]
Thanks Barak - If I'm not mistaken it seems that we're missing the validation of the keys themselves which is the issue that @guy-har found with the paignation

**Comment by nopcoder** [comment]
> Thanks Barak - If I'm not mistaken it seems that we're missing the validation of the keys themselves which is the issue that @guy-har found with the paignation

There is no way to validate the value we keep under kv as we do not encode the message metadata, just the data.
The test use the message type for the model and the secondary index as it worked because the first field in the message was the same type.
Update test code uses the right message type and validates iterate after 'key' works as the index and the secondary now holds different values.

**Comment by N-o-Z** [comment]
> > Thanks Barak - If I'm not mistaken it seems that we're missing the validation of the keys themselves which is the issue that @guy-har found with the paignation
> 
> There is no way to validate the value we keep under kv as we do not encode the message metadata, just the data. The test use the message type for the model and the secondary index as it worked because the first field in the message was the same type. Update test code uses the right message type and validates iterate after 'key' works as the index and the secondary now holds different values.

secondary iterator returns MessageEntry which is key + value, in the unit tests we only validate the value part without the key

**Comment by nopcoder** [comment]
> secondary iterator returns MessageEntry which is key + value, in the unit tests we only validate the value part without the key

Key not found does lookup for "just_a_string/e" find the secondary key and fail to find the value. Is this the test we are after?

**Review by N-o-Z — APPROVED** [review]
LGTM

**Pull request merged**
