### PR TITLE
Fix gitleaks configuration

### PR DESCRIPTION
**Pull request by nopcoder**

### CODE REVIEW

**Review by arielshaqed — APPROVED** [review]
I can understand why this might be better toml than before -- after all, I've never seen a good toml.  And I can see whether it looks better on the action.
But I think we also need to fix the GitHub action: running `gitleaks` failed, the action succeeded.  This should not have happened.
I'm approving because (I assume) it's better than what we had.  But it does *not* fix the issue that the check failed and the action succeeded.

**Review by arielshaqed — CHANGES_REQUESTED** [review]
Sorry, still broken:
```
/usr/bin/docker run --name f44fd7608375460eaa98fda4347570b7_388d1a --label 179394 --workdir /github/workspace --rm -e GOROOT -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/lakeFS/lakeFS":"/github/workspace" 179394:f44fd7608375460eaa98fda4347570b7
fatal: ambiguous argument 'remotes/origin/master...remotes/origin/fix/gitleaks': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
running gitleaks v6.2.0 with the following command👇
gitleaks --pretty --repo-path=/github/workspace --verbose --redact --commit-from= --commit-to= --config=/github/workspace/.gitleaks.toml
INFO[2020-11-23T11:08:00Z] No leaks detected. 1 commits scanned in 553 microseconds 
✅ SUCCESS! Your code is good to go!
------------------------------------
👋 maintaining gitleaks takes a lot of work so consider sponsoring me or donating a little something
https://github.com/sponsors/zricethezav
https://www.paypal.me/zricethezav
```

**Comment by nopcoder** [comment]
> Sorry, still broken:
> 
> ```
> /usr/bin/docker run --name f44fd7608375460eaa98fda4347570b7_388d1a --label 179394 --workdir /github/workspace --rm -e GOROOT -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/lakeFS/lakeFS":"/github/workspace" 179394:f44fd7608375460eaa98fda4347570b7
> fatal: ambiguous argument 'remotes/origin/master...remotes/origin/fix/gitleaks': unknown revision or path not in the working tree.
> Use '--' to separate paths from revisions, like this:
> 'git <command> [<revision>...] -- [<file>...]'
> running gitleaks v6.2.0 with the following command👇
> gitleaks --pretty --repo-path=/github/workspace --verbose --redact --commit-from= --commit-to= --config=/github/workspace/.gitleaks.toml
> INFO[2020-11-23T11:08:00Z] No leaks detected. 1 commits scanned in 553 microseconds 
> ✅ SUCCESS! Your code is good to go!
> ------------------------------------
> 👋 maintaining gitleaks takes a lot of work so consider sponsoring me or donating a little something
> https://github.com/sponsors/zricethezav
> https://www.paypal.me/zricethezav
> ```

The configuration file is fixed - but I guess you are talking about the invalid command line argument

**Comment by arielshaqed** [comment]
Dunno if you know or if it's my turn to review, but there's still a fatal error:
> fatal: ambiguous argument 'remotes/origin/master...remotes/origin/fix/gitleaks': unknown revision or path not in the working tree.

Even worse (to my mind) is that the action keeps succeeding even though it does not appear to work.

**Comment by nopcoder** [comment]
> Dunno if you know or if it's my turn to review, but there's still a fatal error:
> 
> > fatal: ambiguous argument 'remotes/origin/master...remotes/origin/fix/gitleaks': unknown revision or path not in the working tree.
> 
> Even worse (to my mind) is that the action keeps succeeding even though it does not appear to work.

Still my turn... I think it is related to how the docker run command, used by git action, passing the commit information.
I'm running the same command locally without an issue.

**Comment by nopcoder** [comment]
can we approve this part - I will look for a better solution for the second one later. thanks.

**Review by arielshaqed — APPROVED** [review]
Yeah, it's the best we can do for now.

Sorry for delay.

**Pull request merged**
