### PR TITLE
Move lakeFS Enterprise and lakeFS Cloud doc pages to top level

### PR DESCRIPTION
**Pull request by talSofer**
Closes https://github.com/treeverse/product/issues/334

### CODE REVIEW

**Comment by itaiad200** [comment]
> 🎊 PR Preview [071bb07](https://github.com/treeverse/lakeFS/commit/071bb07709eb65878ac85f77c2c65ea469319741) has been successfully built and deployed to https://treeverse-lakeFS-preview-pr-7851.surge.sh
> 
> 🕐 Build time: **0.009s**
> 
> [](https://github.com/treeverse/lakeFS/actions/runs/9461317596)
> 
> 🤖 By [surge-preview](https://github.com/afc163/surge-preview)

@talSofer notice that the 2 new top level sections end up in a redirect loop ➿

**Comment by N-o-Z** [comment]
> > 🎊 PR Preview [071bb07](https://github.com/treeverse/lakeFS/commit/071bb07709eb65878ac85f77c2c65ea469319741) has been successfully built and deployed to https://treeverse-lakeFS-preview-pr-7851.surge.sh
> > 🕐 Build time: **0.009s**
> > [](https://github.com/treeverse/lakeFS/actions/runs/9461317596)
> > 🤖 By [surge-preview](https://github.com/afc163/surge-preview)
> 
> @talSofer notice that the 2 new top level sections end up in a redirect loop ➿

I haven't noticed that when opening the preview page

**Review by N-o-Z — APPROVED** [review]
LGTM

**Comment by talSofer** [comment]
> I haven't noticed that when opening the preview page

Thanks @N-o-Z @itaiad200 , the updated preview URL don't have these redirects, I fixed them (see https://github.com/treeverse/lakeFS/pull/7851#issuecomment-2159983528)

**Pull request merged**
