### PR TITLE
Add repository indication for import

### LINKED ISSUE #5978: Import: Add import indication for repository level
Add key in refstore to indicate that an import has occurred in repository level.
We'll use the following:
GET import endpoint with key = ""
When creating a new import - update the key in addition to the importID key.
@eladlachmi FYI

### PR DESCRIPTION
**Pull request by N-o-Z**
### Linked Issue

Closes #5978

---

### CODE REVIEW

**Review by nopcoder — CHANGES_REQUESTED** [review]
Can we populate repository information once?
The suggested solution is an exception that we need to remember not to delete and it changes the API in a strange way that makes something that looks like required to non required.

**Comment by N-o-Z** [comment]
> Can we populate repository information once? The suggested solution is an exception that we need to remember not to delete and it changes the API in a strange way that makes something that looks like required to non required.

@nopcoder Thanks! 
Setting the repository information only once means we will still need to perform a KV operation (set-if nil), still incurring a kv operation.
I don't think the change is that strange - the alternative is introducing a whole new API specifically for it

**Comment by nopcoder** [comment]
> > Can we populate repository information once? The suggested solution is an exception that we need to remember not to delete and it changes the API in a strange way that makes something that looks like required to non required.
> 
> @nopcoder Thanks! 
> Setting the repository information only once means we will still need to perform a KV operation (set-if nil), still incurring a kv operation.
> I don't think the change is that strange - the alternative is introducing a whole new API specifically for it

From kv operations I do not suggest adding anything new. Just have an indicator in the repository level.
The API change will have to fetch the repository level indicators or optional parameters while calling get repository that will return this information. 
overloading the get status looks a one time thing that forces the API to have two jobs.
@eladlachmi do we have more repository level indicators that we plan?

**Comment by N-o-Z** [comment]
> > > Can we populate repository information once? The suggested solution is an exception that we need to remember not to delete and it changes the API in a strange way that makes something that looks like required to non required.
> > 
> > 
> > @nopcoder Thanks!
> > Setting the repository information only once means we will still need to perform a KV operation (set-if nil), still incurring a kv operation.
> > I don't think the change is that strange - the alternative is introducing a whole new API specifically for it
> 
> From kv operations I do not suggest adding anything new. Just have an indicator in the repository level. The API change will have to fetch the repository level indicators or optional parameters while calling get repository that will return this information. overloading the get status looks a one time thing that forces the API to have two jobs. @eladlachmi do we have more repository level indicators that we plan?

I am not excited about the idea of adding a new field to the repo protobuf for something which is not a functional feature, and could be potentially be removed at any given time. With the current solution we can block this functionality if needed with only minimal code changes and without any impact to user or any leftovers that we'll have to live with forever

**Comment by arielshaqed** [comment]
Oooh, I would _really_ like to have per-repo user metadata!  There are several features related to OTFs and also _non-_ Open Table Formats that would greatly benefit from such a thing.  Generally we should do an AmazonAWS and put user metadata on everything: entire installation, each repo, every branch, ...

Still not convinced?  We already have these APIs that say "add my *uniquely special* metadata for comm prefs / gc rules / branch protection", and possibly more.  We have this discussion each time we need another one -- and meanwhile we don't allow our users to get this exact same thing.

**Comment by N-o-Z** [comment]
Will be completed in #6069

**Pull request closed without merging**
