### PR TITLE
Include v1.3.1 in compatibility tests

### PR DESCRIPTION
**Pull request by nopcoder**

### CODE REVIEW

**Comment by arielshaqed** [comment]
Can you run compatibility tests on this branch, please?  It should support workflow_dispatch :-)

**Review by arielshaqed — COMMENTED** [review]
Thanks!

Assuming compatibility tests pass, this is great - please pull :-)

**Comment by nopcoder** [comment]
> Thanks!
> 
> Assuming compatibility tests pass, this is great - please pull :-)

Green!

**Review by arielshaqed — APPROVED** [review]
> > Thanks!
> > Assuming compatibility tests pass, this is great - please pull :-)
> 
> Green!

🍏 A wise man once said:
> please pull

**Pull request merged**
