### PR TITLE
Feature/tree

### PR DESCRIPTION
**Pull request by tzahij**
Initial PR, not working, not tested yet

---
This change is [Reviewable](https://reviewable.io/reviews/treeverse/lakefs/984)

### CODE REVIEW

**Comment by itaiad200** [comment]
The PR has 36 commits in it, and my guess is that most of them are not yours and from before latest pruning of master branch. This can cause chaos if merged, not even sure if this can get in.

So - Can you please start off fresh by copying the files and base your changes on origin/master?

**Review by nopcoder — COMMENTED** [review]
partial review I'll continue later

**Comment by arielshaqed** [comment]
This has many commits from being merged from master.  That just makes reviewing harder.  Could you please rebase?

**Comment by ozkatz** [comment]
Work from this PR was adapted and merged in a different set of PRs. Closing for now.

**Pull request closed without merging**
