### PR TITLE
Remove "lakefs diagnose" and adapter ValidateConfiguration

### PR DESCRIPTION
**Pull request by arielshaqed**
This was used only to validate that S3 buckets are configured with
expiration suited for the disused expiry mechanism.  It appears never to
have been used.

This refactoring (in the sense of pushing it into a river) makes #2684
easier.

### CODE REVIEW

**Comment by arielshaqed** [comment]
Reviewers: @ozkatz for product (to verify this is OK to kill), @nopcoder to be happy that I sometimes delete code and that he has no long-term plans for this command and/or block adapter API.

**Comment by arielshaqed** [comment]
@ozkatz says "kill it with fire", so is off the hook for reviewing.  Thanks!

**Review by nopcoder — COMMENTED** [review]
👍 Less code

**Comment by nopcoder** [comment]
just re-generate the commands docs

**Review by arielshaqed — COMMENTED** [review]
Thanks!

**Review by nopcoder — APPROVED** [review]

**Pull request merged**
