### PR TITLE
Make lakeFS multimodule: move logging, cache, testutil.Must to new lakefs/util module

### PR DESCRIPTION
**Pull request by arielshaqed**
## What

* Make lakeFS a multi-module workspace.

  Here's a [brief tutorial](https://go.dev/doc/tutorial/workspaces) on multi-module workspaces.  In brief, this lets us create a small module github.com/treeverse/lakefs/util that can be included without all the dependencies of github.com/treeverse/lakefs.
* Put logging, cache, and testutil.Must* into the util/ module.
  * Ensure tests still run there.

## Tips for reviewing

- The commits kinda make sense, you probably want to review by commit.
- Take a look at the result:
  - Will it be easy to use logging/ and cache/ in their new locations?
  - Is it worth doing in order to isolate their dependencies?  Is util/go.mod an improvement?
- Historically there was some disagreement about whether multi-module workspaces should be used like this.  What do you think?
- This PR breaks an implied guarantee about semantic version _of Go modules_.  But not one of the guarantees that we made in the [Towards 1.0](https://docs.lakefs.io/understand/towards-1.0-sdk.html) post.  And [this search](https://github.com/search?q=%22github.com%2Ftreeverse%2Flakefs%2Fpkg%22+-org%3Atreeverse+NOT+is%3Afork+-org%3Aep-infosec+-org%3A2lambda123+-org%3Aungtb10d&type=code) shows no real uses of this repo.

### CODE REVIEW

**Comment by N-o-Z** [comment]
@arielshaqed I looked at the PR but I feel we should have a discussion on this with a larger audience.
I went through the points you wrote and overall it seems to make sense but I would like to hear any objections if there are any to this change.
Also - if we already created a new module, maybe it's better to separate the test logic and the utilities?

**Comment by Jonathan-Rosenberg** [comment]
@arielshaqed what's the reasoning behind this PR?

**Comment by arielshaqed** [comment]
> @arielshaqed what's the reasoning behind this PR?

## Mark safe-to-reuse packages from lakeFS

These are useful packages: we already use them in several other locations.  I want to indicate particularly safe packages to use.

## Control dependencies of these general packages

As a by-product, this way prevents "small" changes that suddenly bring in large portions of the lakeFS code.  (For instance, IIRC we've had versions where logging/ ended up depending on portions of Graveler, just because they didn't log.  And we discovered those when we suddenly got import loops.)

**Comment by ozkatz** [comment]
does this mean we’re closer to carving out a lakeFS Go client lib that is consumable by other projects?

**Comment by arielshaqed** [comment]
@ozkatz :
> does this mean we’re closer to carving out a lakeFS Go client lib that is consumable by other projects?

It would be possible either way.  This PR should make it easier, because it breaks down some dependency walls.

**Pull request closed without merging**
