### PR TITLE
improve grammar  in licence docs 

### PR DESCRIPTION
**Pull request by arpitsingh134**
I have made some improvement in license   doc and readme

### CODE REVIEW

**Comment by arpitsingh134** [comment]
oj

**Comment by arpitsingh134** [comment]
ok

**Comment by arielshaqed** [comment]
Hi @arpitsingh134 

Unfortunately the Apache License is  a fixed legal work and there will be legal issues with any changes to it.  I am closing this pull request.  Please open a new one with the non-license changes.

Thanks!

**Comment by arpitsingh134** [comment]
ok thanks

**Pull request closed without merging**
