### PR TITLE
Upgrade version of `oapi-codegen`

### PR DESCRIPTION
**Pull request by jamietanna**
To get the latest features and bug fixes, we should bump to the latest
version of the library.

Thanks for using oapi-codegen! 

Note that I've not updated https://github.com/treeverse/lakeFS/blob/16cf7691f6b0981565c3563c6e9756e17754a32b/pkg/api/serve.go#L100 - I'd recommend y'all as the maintainers have a look and see if there's anything that can be tweaked

May also be worth reviewing the upstream templates vs our versions here, in case there's anything else useful to bring in changes wise

### CODE REVIEW

**Comment by arielshaqed** [comment]
This looks really neat and a good idea!  @jamietanna : did you manage to run `make build test`?  This is roughly what [this test](https://github.com/treeverse/lakeFS/actions/runs/7987779703/job/22342311517?pr=7493) tries to do and fails -- it looks like some dependency is missing, but after I run `go get github.com/oapi-codegen/v2/runtime` I get other breakages in building the generated code.  (I pushed it on branch chore/oapi here, so you can just see it in 58a413a3c2b909cebb20f478d0402244efb133a8.)

Perhaps we're generating the files incorrectly?  Or some further template updates are missing?

**Comment by arielshaqed** [comment]
The new code has stricter typing for enums, which is cool!  I fixed the relevant compilation breakage in 4d335e3695a76a07520cc90b81234b404243532d, but now [this func](https://github.com/treeverse/lakeFS/blob/e55669c3d7afe6c6b103e6fc61af3ef663f13c68/pkg/api/tmpl/inline.tmpl#L22-L39) is broken.

This version bump is turning into a somewhat larger fix than I expected.  I'd of course be happily grateful for your time to advise us on doing it -- but will you have time for us?

Again: thanks!

**Comment by jamietanna** [comment]
Thanks for your changes to help with this too - I think these latest changes _should_ pass - I'm just running through the tests locally now

**Comment by jamietanna** [comment]
Oh hmm I see https://github.com/treeverse/lakeFS/pull/7532

**Comment by jamietanna** [comment]
OK, so my confusion with getting the changes appears to be because we've got a mix of files that are and aren't committed - think I've managed to get there now

**Comment by jamietanna** [comment]
https://github.com/treeverse/lakeFS/pull/7533 will be a prerequisite, then it'll be easier to see the difference when doing the upgrade :+1:

**Pull request closed without merging**
