### PR TITLE
Feature/react with vite

### PR DESCRIPTION
**Pull request by ozkatz**

### CODE REVIEW

**Comment by arielshaqed** [comment]
> This pull request **introduces 3 alerts** when merging [350e451](https://github.com/treeverse/lakeFS/commit/350e4511b961c193334b2b92528ee4e5ce0056fb) into [6573887](https://github.com/treeverse/lakeFS/commit/6573887303e8909b0727d11c8239b3fb4bd26936) - [view on LGTM.com](https://lgtm.com/projects/g/treeverse/lakeFS/rev/pr-a79ec2a21f5190e8a53980ddd2d8817fcf413f18)
> 
> **new alerts:**
> 
>     * 3 for Unused variable, import, function or class

:-/

**Review by arielshaqed — COMMENTED** [review]
Also: what happened to `package-lock.json`?

**Review by nopcoder — CHANGES_REQUESTED** [review]
My only concern is related to the additional files generated by the tool, like:
webui/index.html
webui/src/App.jsx

They added react icon and something like "hello"/"start" page with link to vitejs website.

Think they should be out.

**Comment by ozkatz** [comment]
> Also: what happened to `package-lock.json`?

The dependency tree is almos completely different since the entire dev dependency tree (which makes up for the majority of packages) is coming from vite.

**Comment by ozkatz** [comment]
> My only concern is related to the additional files generated by the tool, like:
> webui/index.html
> webui/src/App.jsx
> 
> They added react icon and something like "hello"/"start" page with link to vitejs website.
> 
> Think they should be out.

@nopcoder removed

**Review by nopcoder — APPROVED** [review]

**Pull request merged**
