### PR TITLE
lakefs spark client bump lakefs sdk to v1

### PR DESCRIPTION
**Pull request by nopcoder**
Close https://github.com/treeverse/lakeFS/issues/6848

### CODE REVIEW

**Review by arielshaqed — COMMENTED** [review]
Please ask @ozkatz if they want lakeFSFS to go to 1.0. There's no technical reason to block this or to want this, but it does mean freezing the configuration interface.
We should consider maybe just 0.20.0 if we plan to go fully presigned or presigned by default.

**Comment by nopcoder** [comment]
@arielshaqed update the issue and the next version for lakeFSFS to v0.11.0
This change will include just a release that uses lakefs-sdk v1.

**Comment by arielshaqed** [comment]
> @arielshaqed update the issue and the next version for lakeFSFS to v0.11.0 This change will include just a release that uses lakefs-sdk v1.

Sure!  It says "after", not "2 days after" :-)  I opened it as a placeholder.  I think we need to make some decisions, so adding them to that issue.

**Comment by nopcoder** [comment]
@arielshaqed Think we need to split the issue or update this one. Yesterday I've updated the issue to include just v1 SDK - not release the v1 for the package as this was part of lakeFS v1.

As we like to have a lakeFSFS package using lakeFS v1 SDK out.
Do you prefer a different issue for this change and removing the v1 blocker from current one?

**Comment by nopcoder** [comment]
Create and associated to a new issue

**Review by arielshaqed — APPROVED** [review]
Great, thanks!

Completely agree we should take a while longer to release lakeFSFS 1.0.0.

**Pull request merged**
