### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by SinithH**

### CODE REVIEW

**Review by arielshaqed — APPROVED** [review]
Thanks!

**Comment by arielshaqed** [comment]
Just some minimal legal requirements before we can merge: https://github.com/treeverse/lakeFS/pull/861#issuecomment-716028461 says


> [CLA assistant check](https://cla-assistant.io/treeverse/lakeFS?pullRequest=861)
> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/treeverse/lakeFS?pullRequest=861) before we can accept your contribution.
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/treeverse/lakeFS?pullRequest=861) it.

**Comment by SinithH** [comment]
> Just some minimal legal requirements before we can merge: [#861 (comment)](https://github.com/treeverse/lakeFS/pull/861#issuecomment-716028461) says
> 
> > [CLA assistant check](https://cla-assistant.io/treeverse/lakeFS?pullRequest=861)
> > Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/treeverse/lakeFS?pullRequest=861) before we can accept your contribution.
> > You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/treeverse/lakeFS?pullRequest=861) it.

Signed it !

**Comment by arielshaqed** [comment]
Thanks!

**Pull request merged**
