### PR TITLE
update generated files to use io.lakefs package

### PR DESCRIPTION
**Pull request by nopcoder**

### CODE REVIEW

**Review by arielshaqed — APPROVED** [review]
This is just `make client-java`,  right?

**Comment by nopcoder** [comment]
yes, but I had to do it twice - it looks like the second run of the generator remove a list of test files from this list

**Comment by nopcoder** [comment]
@arielshaqed Looks like we have an issue with the code gen and the test file - running the step again, it finds the test source files and skip them `(Test files never overwrite an existing file of the same name.)` - but doesn't report them to FILES like it does with the source code.

**Comment by nopcoder** [comment]
Ignoring the FILES will solve this issue for now

**Pull request merged**
