### PR TITLE
docs: update jekyll gem for python docs

### PR DESCRIPTION
**Pull request by nopcoder**

### CODE REVIEW

**Review by N-o-Z — APPROVED** [review]
One question I'm not clear on

**Comment by nopcoder** [comment]
> One question I'm not clear on

where is the question?

**Comment by N-o-Z** [comment]
> > One question I'm not clear on
> 
> where is the question?

That's so weird,  my comment is missing...
I was asking why we use a specific darwin package for the nokogiri

**Comment by nopcoder** [comment]
> > > One question I'm not clear on
> > 
> > 
> > where is the question?
> 
> That's so weird, my comment is missing... I was asking why we use a specific darwin package for the nokogiri

So every time you do `bundle install` it will include the platform you used in the list of bundles and also update the specific platform packages.

I assume the next question will be so - How does it work for our Linux env?
We included ruby platform which means CRuby that runs on all non Windows platform and this is why it works in our CI.

We can explicit add linux as a platform and in this specific case, if we have linux specific implementation it will be added.

**Pull request merged**
