### PR TITLE
Fix uncommitted path for prepare gc

### LINKED ISSUE #4632: Uncommitted GC path contains `s3://` in the path
Root cause: Wrong concatenation of the full uri

### PR DESCRIPTION
**Pull request by itaiad200**
closes #4632

### CODE REVIEW

**Comment by itaiad200** [comment]
Tested locally and the path looks ok now.

**Review by eden-ohana — APPROVED** [review]

**Review by N-o-Z — CHANGES_REQUESTED** [review]
Please add the missing checks in the catalog unit test

**Review by N-o-Z — APPROVED** [review]
I understand we want to fix it fast so we won't block but I don't like this as a permanent solution.
Can we open an issue to handle this better later?

**Comment by itaiad200** [comment]
Opened https://github.com/treeverse/lakeFS/issues/4649

**Pull request merged**
