### PR TITLE
Remove unused funcs in tx.go

### LINKED ISSUE #3078: Remove unused functions in tx.go

### PR DESCRIPTION
**Pull request by DataDavD**
Remove unused functions in tx.go

This PR closes #3078

### CODE REVIEW

**Comment by DataDavD** [comment]
FYI I made this PR pretty quick, but after reviewing code a bit more, I'm wondering if there is a reason this has stayed in the code base but hasn't been used yet. Do we actually want to remove it? Or are the foreseen places or circumstances where these functions will be used in the future?

**Comment by N-o-Z** [comment]
@DataDavD  As best practices we try not to leave unused code in the repository. Worst case - we will re add it when needed

**Review by N-o-Z — APPROVED** [review]
Looks good. Thanks!

**Comment by N-o-Z** [comment]
@DataDavD All checks have passed - you can press the merge button to merge the changes

**Comment by DataDavD** [comment]
Sounds good. I figured that as the case, but just wanted to be sure since I'm not too knowledgeable about the history and roadmap of lakeFS. However, thought it was fine, its in the git history anyways 😄. Thank you for the quick review!

> @DataDavD As best practices we try not to leave unused code in the repository. Worst case - we will re add it when needed

**Comment by DataDavD** [comment]
Great! Unfortunately, it appears I don't have the perms to Merge 😞. Are you able to merge for me when you get a chance? Thanks in advance!

> @DataDavD All checks have passed - you can press the merge button to merge the changes

**Comment by N-o-Z** [comment]
Done, thanks!

**Comment by arielshaqed** [comment]
Hi @DataDavD ,

Thanks for this PR!

Some background / context / legends and origin stories: we used to use PostgreSQL a _lot_ more.  At that time selecting appropriate consistency models made sense.

With #2466 coming up, we have been _removing_ usage of RDBMS features.  So we no longer need these functions, and (I hope) there should be no use for them in the near future.  So IMO you're spot-on that they meeded to go!

**Comment by DataDavD** [comment]
@arielshaqed thanks for the great detailed response/info. It's very helpful. 

That is one of the many things I love about lakeFS/treeverse engineers like you. Y'all are always willing to help out and provide good explanations for everything to make it easy on us new contributors to understand why things have been done, are being done, and will be done.

Also, very excited to hear about #2466 !!!!! 🥳 

Thanks again!

Best,
David

**Pull request merged**
