### PR TITLE
Fix broken link to pyspark.sql.DataFrame.printSchema

### LINKED ISSUE #8110: Fix broken link to `pyspark.sql.DataFrame.printSchema`
The link https://spark.apache.org/docs/3.1.1/api/python/reference/api/pyspark.sql.DataFrame.printSchema.html is broken (404), and it breaks the "Docs PR" job - see [example job run](https://github.com/treeverse/lakeFS/actions/runs/10592977656/job/29354383235?pr=8108#step:8:39).

### PR DESCRIPTION
**Pull request by yonipeleg33**
Closes #8110

### CODE REVIEW

**Review by itaigilo — APPROVED** [review]

**Review by arielshaqed — COMMENTED** [review]
Cool!

Not approving and instead adding @kesarwam and/or @talSofer because it's their page and we're bumping the PySpark version.  Do we want to push it so far ahead?

**Comment by yonipeleg33** [comment]
> > Cool!
> > Not approving and instead adding @kesarwam and/or @talSofer because it's their page and we're bumping the PySpark version. Do we want to push it so far ahead?
> 
> What's the reasoning for the version update? is it broken on the earlier version? @yonipeleg33 was this tested?

@talSofer This link simply does not exist in this version.
If you'll go to the new link, you'll see their documentation's oldest version is 3.3.0, which is already to majors above the old, broken API.
image

So I don't see much point in bumping up 2 majors and _not_ moving to the current latest...

**Comment by itaiad200** [comment]
Merging this since CI is failing. @talSofer feel free to open a different issue for anything that needs to be tested

**Comment by N-o-Z** [comment]
@yonipeleg33 documentation PRs do not require include-changelog label

**Pull request merged**
