### PR TITLE
Support presigned image URLs in markdown

### LINKED ISSUE #6412: [Bug]: UI Markdown Renderer not using presign URL to get images
### What happened?

# What 

When rendering Markdown files, the UI loads images. 
The problem is that when getting those images from lakeFS the UI ignores `presign` config (i.e sample repository, sample data in a custom repository or just any custom Markdown that fetches files from `lakefs://`).

# Why

Those images are rendered in [CustomMarkdownRenderer](https://github.com/treeverse/lakeFS/blob/master/webui/src/pages/repositories/repository/fileRenderers/CustomMarkdownRenderer.tsx) component which in turns uses [imageUriReplacer](https://github.com/treeverse/lakeFS/blob/master/webui/src/lib/remark-plugins/imageUriReplacer.ts#L33C20-L33C31) to fetch the images to load. The request to download the image doesn't use `presign` hence downloading directly from lakeFS server. 

# Impact 

Besides the unexpected behavior and the extra work lakeFS server does + extra cost it's breaking  in case the storage credentials (S3,GCS,AZ) does not allow lakeFS server directly to get objects then the Markdown rendering breaks. 
        
# Steps to Reproduce:

1. Setup lakeFS server with S3 and all the [IAM permissions](https://docs.lakefs.io/reference/presigned-url.html#configuring-lakefs-to-use-presigned-urls) for using pre-sign from lakeFS
2. Configure the UI to use presign: 
```yaml
blockstore:
  type: s3
  s3:
    disable_pre_signed_ui: false
    disable_pre_signed: false
```
4. Create a repository > Select `Add sample data, hooks, and configuration` 
5. In the browser network tab  see many GET requests for resources that does not specify `presign: true`. (i.e `/api/v1/repositories/first1/refs/main/objects?path=images%2Fcreate-lakefs-branch.png`)

image

Screen Shot 2023-08-15 at 16 18 20

### Expected behavior

- Markdown renderer in the UI to include `presign` flag and respect it when downloading images.  
- The Markdown to render correctly even if lakeFS is not allowed to do `Get` directly. 

### lakeFS version

v0.105.0

### How lakeFS is installed

locally

### Affected clients

ui

### Relevant log output

```shell
level=error msg="failed to get S3 object bucket my-bucket/remote/first1 key data/1234567/11122324123" func="pkg/logging.(*logrusEntryWrapper).Errorf" file="build/pkg/logging/logger.go:285" error="AccessDenied: Access Denied\n\tstatus code: 403, request id: 123, host id: ..." host=lakefs-presign.us-east-1.lakefscloud.ninja method=GET operation=GetObject operation_id=GetObject path="/api/v1/repositories/first1/refs/main/objects?path=images%2Fhooks-07.png" request_id=... service_name=rest_api user=admin
```

### Contact details

_No response_

### PR DESCRIPTION
**Pull request by eladlachmi**
Closes #6412 

This isn't a bug per se since we decided not to support pre-signed URLs when this was implemented.  
This PR adds this support.

presigned-image-md

Two things to note:

1. `react-markdown` doesn't support async plugins (see [here](https://github.com/remarkjs/react-markdown/issues/680)). To get around this, I've replaced `react-markdown` with `@beeswax/react-markdown-async`. This is not the official package and isn't heavily used. I've reviewed the code to ensure nothing fishy is going on. I've also locked down the package version. Since npm package versions are immutable, this shouldn't be a major security risk. However, this isn't ideal and we should plan to follow this up with a move from `react-markdown` to `react-remark`
2. In the issue, you mentioned image URLs using API endpoints directly, e.g., `/api/v1/repositories/first1/refs/main/objects?path=images%2Fcreate-lakefs-branch.png`. This is not the intended use case. The supported URLs for replacement are `lakefs://` URIs and relative paths. Using API endpoints as image URLs in the quickstart is a mistake. We should discourage this practice because it essentially embeds specific API endpoints, path parameters, and querystring parameters in MD files. This is exactly the thing that the `lakefs://` URI scheme is supposed to abstract away.

### CODE REVIEW

**Review by N-o-Z — COMMENTED** [review]
Maybe I'm missing something,
Anywhere presign is hardcoded to false we need to pass to configuration parameters for presign no?

**Review by Isan-Rivkin — CHANGES_REQUESTED** [review]
@eladlachmi Code looks good, thank you! 
I was wondering about the package you added on [npm](https://www.npmjs.com/package/@beeswax/react-markdown-async) it leads to an incorrect [Github repository](https://github.com/remarkjs/react-markdown) with 12.3K starts, that's odd! 
I wanted to inspect it on Github, it's probably me missing something. Could you kindly point me to the public source code?

**Comment by eladlachmi** [comment]
> Could you kindly point me to the public source code?

@Isan-Rivkin This version of the package doesn't have its own GitHub repo. It's a fork of the original package, but the forked repo isn't public for whatever reason. The creator of this package didn't update the README.md or the package.json (except for the package name), so the links are to the original repo. You can view the code on the code tab of the [package page](https://www.npmjs.com/package/@beeswax/react-markdown-async).

**Comment by Isan-Rivkin** [comment]
@eladlachmi The code in the PR - no comments, LGTM.  

But, this package raises a big Red Flag to me due to few reasons: 

- First, there's lack of visibility to the source code in a more public "judging" manner, such a Github.
- Second, The download usage is basically 0 since 34 weekly downloads is reflecting automated scans. 
- Third, I looked at the code on NPM tab as suggested but really felt like it's not the right context to do a security review to a package. Looking at [Snyk](https://snyk.io/advisor/npm-package/@beeswax/react-markdown-async) I can see a low healthy score. 

This means that even if the package good, we will lower our overall security score of lakeFS project. 
Especially since it's in the critical path (access to users data) I am very hesitant. 
Can we use an alternative?

**Comment by eladlachmi** [comment]
@Isan-Rivkin I've refactored the code to move from `react-markdown` to `rehype-react` + `remark-rehype`, which is the recommended way to go according to the `unified` maintainers. I've also upgraded all plugins (incl. our custom plugin) to the latest version for compatibility with the latest version of `rehype-react` and `remark-rehype`.  
You'll notice I changed `CustomMarkdownRenderer.tsx` to `CustomMarkdownRenderer.jsx`. I tried to type this correctly for the better part of the last hour, and I'll admit, I gave up 😔 Since it has a simpler return value now, the type validation isn't as critical, so I'll take the L.

**Review by Isan-Rivkin — APPROVED** [review]
LGTM, Looks wonderful very nice improvement!

**Pull request merged**
