### PR TITLE
Fix/repo path #835

### PR DESCRIPTION
**Pull request by shamikakumar**
Implemented #835

### CODE REVIEW

**Comment by itaiad200** [comment]
Hey @shamikakumar , thanks for your effort!
Couple of things:
1. Handling big repo/branch names. It looks truncated:
image

2. The basePath isn't close enough to the filename, which makes it less clear that the 2 forms the lakeFS path.

Requesting for the above changes, once fixed I'll be happy to approve and merge.

**Review by itaiad200 — CHANGES_REQUESTED** [review]
Requesting changes for position of base path and long repo/branch names.

**Comment by shamikakumar** [comment]
@itaiad200 made a few changes, do review and let me know

**Comment by itaiad200** [comment]
Looks much better! Approved.

**Review by itaiad200 — APPROVED** [review]

**Pull request merged**
