### PR TITLE
Adding Class to all images for GTM Purpose

### PR DESCRIPTION
**Pull request by JamilAhmad**
Need to add a class attribute with value (tmtrack) to all images for google tag manager as per Noy Davidson instruction, it will be time-consuming to add class to all images one by one so I have added a script that will do this process globally, please review and approve if all good

### CODE REVIEW

**Comment by JamilAhmad** [comment]
we can use both $ or Jquery both works, we are only about adding class to all images it's not about clickable or label, etc.
Noy Davidson mentioned that He needs the same Class for all images that's why need to run that script

**Comment by nopcoder** [comment]
The $ is to be consistent with the rest of the code in the same file.
About the images, @NoyDavidson2 from what I understand we already get notified of all images getting clocked, and we like to select just the clickable?

**Comment by NoyDavidson2** [comment]
@JamilAhmad After debugging the problem, it seems that the problem has been solved by filtering images on Google Tag Manager. 
No need to add the unique class to images. Thanks!

**Comment by JamilAhmad** [comment]
Okay sounds good @NoyDavidson2

**Pull request closed without merging**
