### PR TITLE
GC+: Fix LakeFSCommitInputFormat getSplits

### LINKED ISSUE #4713: GC+: CommittedAddressLister fails when repository is empty
Running GC on a newly created repository fails due to trying to read the `_lakefs` directory.
This is due to a call to fs.listFiles in the LakeFSAllRangesInputFormat:getSplits

```
java.io.FileNotFoundException: No such file or directory: s3a://niro-test/UGC/_lakefs
	at org.apache.hadoop.fs.s3a.S3AFileSystem.s3GetFileStatus(S3AFileSystem.java:2310)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.innerGetFileStatus(S3AFileSystem.java:2204)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.getFileStatus(S3AFileSystem.java:2143)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.innerListFiles(S3AFileSystem.java:3148)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.listFiles(S3AFileSystem.java:3129)
	at io.treeverse.clients.LakeFSAllRangesInputFormat.getSplits(LakeFSInputFormat.scala:224)
	at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:131)
	at org.apache.spark.rdd.RDD.$anonfun$partitions$2(RDD.scala:300)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:296)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.$anonfun$partitions$2(RDD.scala:300)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:296)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.$anonfun$partitions$2(RDD.scala:300)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:296)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.$anonfun$partitions$2(RDD.scala:300)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:296)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.$anonfun$partitions$2(RDD.scala:300)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:296)
	at org.apache.spark.rdd.RDD.getNumPartitions(RDD.scala:316)
	at org.apache.spark.scheduler.DAGScheduler.createShuffleMapStage(DAGScheduler.scala:438)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$getOrCreateShuffleMapStage$1(DAGScheduler.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scala.collection.generic.TraversableForwarder.foreach(TraversableForwarder.scala:38)
	at scala.collection.generic.TraversableForwarder.foreach$(TraversableForwarder.scala:38)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.getOrCreateShuffleMapStage(DAGScheduler.scala:394)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$getOrCreateParentStages$1(DAGScheduler.scala:580)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
	at scala.collection.TraversableLike.map(TraversableLike.scala:285)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:278)
	at scala.collection.mutable.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:50)
	at scala.collection.SetLike.map(SetLike.scala:105)
	at scala.collection.SetLike.map$(SetLike.scala:105)
	at scala.collection.mutable.AbstractSet.map(Set.scala:50)
	at org.apache.spark.scheduler.DAGScheduler.getOrCreateParentStages(DAGScheduler.scala:579)
	at org.apache.spark.scheduler.DAGScheduler.createResultStage(DAGScheduler.scala:564)
	at org.apache.spark.scheduler.DAGScheduler.handleJobSubmitted(DAGScheduler.scala:1115)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2395)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2387)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2376)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
22/11/30 16:35:22 INFO DAGScheduler: Job 0 failed: count at UncommittedGarbageCollector.scala:151, took 0.515174 s
Exception in thread "main" java.io.FileNotFoundException: No such file or directory: s3a://niro-test/UGC/_lakefs
	at org.apache.hadoop.fs.s3a.S3AFileSystem.s3GetFileStatus(S3AFileSystem.java:2310)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.innerGetFileStatus(S3AFileSystem.java:2204)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.getFileStatus(S3AFileSystem.java:2143)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.innerListFiles(S3AFileSystem.java:3148)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.listFiles(S3AFileSystem.java:3129)
	at io.treeverse.clients.LakeFSAllRangesInputFormat.getSplits(LakeFSInputFormat.scala:224)
```

### PR DESCRIPTION
**Pull request by N-o-Z**
closes #4713

### CODE REVIEW

**Comment by johnnyaug** [comment]
@N-o-Z:
When you create a dataframe using a repository name, the error is a bug and I would indeed expect an empty dataframe.

However, note that instead of a repository name you can supply a storage namespace (a mere path). If the path doesn't exist - I expect an error, and this suggested fix swallows it.

Suggestions:
1. Only return an empty dataframe when a repository is given, keep the error for non-existing storage namespace.
(OR)
2. Don't fix.

**Review by nopcoder — APPROVED** [review]
Looks good to me

**Comment by N-o-Z** [comment]
> @N-o-Z: When you create a dataframe using a repository name, the error is a bug and I would indeed expect an empty dataframe.
> 
> However, note that instead of a repository name you can supply a storage namespace (a mere path). If the path doesn't exist - I expect an error, and this suggested fix swallows it.
> 
> Suggestions:
> 
> 1. Only return an empty dataframe when an empty repository is given, keep the error for non-existing storage namespace.
>    (OR)
> 2. Don't fix.

Thanks @johnnyaug,

Decided not to fix for now, taking into account that the repository namespace is already checked beforehand, and that we will fail if it doesn't exist

**Comment by johnnyaug** [comment]
@N-o-Z - I meant don't fix as in do not merge this PR. Where exactly is the storage namespace checked for existence?

**Pull request merged**
