### PR TITLE
Grammatical correction

### PR DESCRIPTION
**Pull request by Lavanyamanohar11**
I made a small grammatical correction, which will improve the quality of your readme file.

### CODE REVIEW

**Review by arielshaqed — COMMENTED** [review]
Thanks!

Not approving because I prefer brevity.  Not rejecting to have an opportunity to understand better.

I would be happy to include this if you could find some more definitive recommendation.  I am not sure (that...) there is agreement on eliding "that".  E.g. https://www.merriam-webster.com/dictionary/ensure give two "Recent Examples on the Web", and both elide the word.  https://english.stackexchange.com/questions/349598/to-ensure-vs-to-ensure-that-subject-predicate has some recommendation to include the word, but that is far from consensual (or even of overwhelming interest on that page).

Do you have something more definitive for us to use?

**Comment by Lavanyamanohar11** [comment]
Thanks for your review!

**Comment by arielshaqed** [comment]
> Thanks for your review!

Sure!  How would you like to proceed?  Given that we are swamped with grammatical fixes, many of which conflict with each other, I see these 2 routes:
* Add a comment with a definitive recommendation when to use "that" and when to avoid it, as per my previous comment.
* Decide that we should revisit this issue later.
(There may be other routes, do feel free to explain some third route and then pick it!)

Thanks!

**Comment by arielshaqed** [comment]
Closing due to inability to re-establish contact.  Please feel free to re-open when ready to proceed on above comments!

**Pull request closed without merging**
