### PR TITLE
Fix: return bad request on reset branch with unknown type 

### PR DESCRIPTION
**Pull request by nopcoder**
Expect to return status not found while returns no content status code.

Close https://github.com/treeverse/lakeFS/issues/7219

### CODE REVIEW

**Review by arielshaqed — CHANGES_REQUESTED** [review]
The old code is definitely a bug.

But I don't understand the new code.  The client sent an invalid request, there is nothing "not found" here.  It's exactly like hitting an invalid endpoint -- `type` could easily be a path parameter.  The other example is import creation type: if you pass an unknown value, `func GetImportType` returns `ErrInvalidValue`, which is a 400 Bad Request.

**Comment by nopcoder** [comment]
> The old code is definitely a bug.
> 
> But I don't understand the new code. The client sent an invalid request, there is nothing "not found" here. It's exactly like hitting an invalid endpoint -- `type` could easily be a path parameter. The other example is import creation type: if you pass an unknown value, `func GetImportType` returns `ErrInvalidValue`, which is a 400 Bad Request.

True, just say that falling to our of the scope will override the status code to no content after we wrote content.
Fixing the status code to bad request.

**Comment by nopcoder** [comment]
@arielshaqed after I've updated the code I've opened another issue https://github.com/treeverse/lakeFS/issues/7220

The code just updated should not get to execute as it should have been blocked by the middleware.

**Review by arielshaqed — APPROVED** [review]
Thanks!

**Comment by nopcoder** [comment]
> Thanks!

Thank you!

**Pull request merged**
