### PR TITLE
Use logging.FromContext instead of logging.Default where possible

### LINKED ISSUE #2682: Put request_id on (almost) every log
All logs made specifically for handling a request should include a request_id field.  This includes e.g. database queries, AWS operations, etc., but possibly **not** things like cache expiries where a particular request is not responsible for the expiry.  (When a cache expiry causes issues, a stronger correlating factor between cache expiry and Bad Things Happening to a request is concurrency with expiry -- request IDs are not necessary for this.)

### PR DESCRIPTION
**Pull request by arielshaqed**
Loggers created using `logging.FromContext` include a request ID field,
allowing readers to thread together actions performed for the same request.
Also in future they allow us to add _additional_ fields, for example to
distinguish S3 from lakeFS API operations deep inside the call tree.

Rename `logging.Default` to something more descriptive but perhaps less
pleasant, to encourage calling `logging.FromContext`.

Fixes #2682.

### CODE REVIEW

**Comment by arielshaqed** [comment]
Reviewers, this one is probably easiest to discuss by commit:
* da8b2c0596d26e50a8841badc48fe0b28acdb514 is all about using `logging.FromContext(ctx)` instead of `logging.Default()`.  We place fields (`request_id`) on the context, and this is the only foolproof way to determine the flow of logs for a particular request.
* d8530cd12ff9747007935203b87fae04891c9c07 and 666e0c4e9 try to make it harder to use `logging.Default()` in future, by changing its name _to be less appealing_.  This is intentional - whenever a context is available, `logging.FromContext` is the right choice!

**Review by nopcoder — CHANGES_REQUESTED** [review]
The adapter use of ctx for logging is great.
But renaming the Default() to ContextUnavailable() looks like we try to force the use of context why we ask for default logger.
Can we rename it back?

**Comment by arielshaqed** [comment]
> The adapter use of ctx for logging is great. But renaming the Default() to ContextUnavailable() looks like we try to force the use of context why we ask for default logger. Can we rename it back?

Yes, indeed!  I really want to make it unpleasant to use a logger without providing a context.  It is almost always correct to provide a context to get a logger.

Would you be happier if I improved its [godoc](https://github.com/treeverse/lakeFS/pull/6312/files#diff-ad9f4a06943faedef105d1cf1bb3bdc46b08986dfbdb1cff3025ef0df3cea56bR329-R331)?

**Comment by nopcoder** [comment]
> > The adapter use of ctx for logging is great. But renaming the Default() to ContextUnavailable() looks like we try to force the use of context why we ask for default logger. Can we rename it back?
> 
> Yes, indeed! I really want to make it unpleasant to use a logger without providing a context. It is almost always correct to provide a context to get a logger.
> 
> Would you be happier if I improved its [godoc](https://github.com/treeverse/lakeFS/pull/6312/files#diff-ad9f4a06943faedef105d1cf1bb3bdc46b08986dfbdb1cff3025ef0df3cea56bR329-R331)?

No need to improve the godocs - approved.
Will try to think of a better way of using it.
Usually I'll have a logger in place and just need to pass the context - don't want that to be mix with getting a fresh logger from context.
If I'll have something better I'll suggest in a different PR.

**Review by nopcoder — APPROVED** [review]

**Comment by arielshaqed** [comment]
> > > The adapter use of ctx for logging is great. But renaming the Default() to ContextUnavailable() looks like we try to force the use of context why we ask for default logger. Can we rename it back?
> > 
> > 
> > Yes, indeed! I really want to make it unpleasant to use a logger without providing a context. It is almost always correct to provide a context to get a logger.
> > Would you be happier if I improved its [godoc](https://github.com/treeverse/lakeFS/pull/6312/files#diff-ad9f4a06943faedef105d1cf1bb3bdc46b08986dfbdb1cff3025ef0df3cea56bR329-R331)?
> 
> No need to improve the godocs - approved. Will try to think of a better way of using it. Usually I'll have a logger in place and just need to pass the context - don't want that to be mix with getting a fresh logger from context. If I'll have something better I'll suggest in a different PR.

Thanks... pulling!

I've been thinking about your idea.  The point is that we _already_ had `Logger.WithContext`: it adds the context onto an existing logger.  But _nobody used it_!  One way to force it would be to call Logger-without-context "LoggerBuilder" or "LoggerTemplate", and not have any logging methods on it.  And you'd need to call "LoggerBuilder.WithTemplate" to get a Logger.  Anyway, that's for another day.

**Pull request merged**
