### PR TITLE
Avoid panics after errors in log-commits

### LINKED ISSUE #5955: When LogCommits has an error in the worker, it panics
Example log:
/go/pkg/mod/github.com/alitto/pond@v1.8.2/pond.go:422 +0x14d
created by github.com/alitto/pond.(*WorkerPool).maybeStartWorker
	/go/pkg/mod/github.com/alitto/pond@v1.8.2/worker.go:32 +0xd3
github.com/alitto/pond.worker({0x5396228, 0xc000702240}, 0xc0000d8690?, 0x1f378a9?, 0xc00075c300, 0xc01b0dcda0)
	/go/pkg/mod/github.com/alitto/pond@v1.8.2/pond.go:453 +0x77
github.com/alitto/pond.(*WorkerPool).executeTask(0xc0000d8600, 0x2?, 0x0?)
	/go/pkg/mod/github.com/alitto/pond@v1.8.2/group.go:62 +0x93
github.com/alitto/pond.(*TaskGroupWithContext).Submit.func1()
	/build/pkg/catalog/catalog.go:1155 +0x286
github.com/treeverse/lakefs/pkg/catalog.(*Catalog).listCommitsWithPaths.func1.1()
	/usr/local/go/src/runtime/panic.go:884 +0x212
panic({0x1bf6580, 0x537ecd0})
	/go/pkg/mod/github.com/alitto/pond@v1.8.2/pond.go:436 +0x4c
github.com/alitto/pond.(*WorkerPool).executeTask.func1()
	/go/pkg/mod/github.com/alitto/pond@v1.8.2/pond.go:26 +0x27
github.com/alitto/pond.defaultPanicHandler({0x1bf6580, 0x537ecd0})
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.Stack()
Stack trace: goroutine 11164622 [running]:
Worker exits from a panic: send on closed channel

### PR DESCRIPTION
**Pull request by itaiad200**
closes #5955

### CODE REVIEW

**Review by nopcoder — CHANGES_REQUESTED** [review]
As discussed - lets leverage workerGroup.TaskGroup.Wait() to wait for all tasks to complete.

**Review by nopcoder — CHANGES_REQUESTED** [review]
As discussed - lets leverage workerGroup.TaskGroup.Wait() to wait for all tasks to complete.

**Comment by itaiad200** [comment]
> As discussed - lets leverage workerGroup.TaskGroup.Wait() to wait for all tasks to complete.

@nopcoder That's what I did, didn't I? I still need the `workerGroup.Wait()` since I do want to exit on the first error, before all tasks exit.

**Review by nopcoder — APPROVED** [review]
LGTM. my comment was before I saw your new commit - you are fast :)

**Pull request merged**
