### PR TITLE
Add physical address to "lakectl fs stat"

### LINKED ISSUE #1221: lakectl stat command should return physical address
Physical address is part of the lakeFS API stat response.
It should be added to the lakectl too.

### PR DESCRIPTION
**Pull request by arielshaqed**
Also fix the command -- it was parsing args incorrectly (not sure how it worked).

Fixes #1221.

### CODE REVIEW

**Comment by arielshaqed** [comment]
Oh yeah, forgot a textshot:
```
ariels@redqueen:~/dev/lakeFS$ ./lakectl fs stat lakefs://foo@trunk/first 
Path: first
Modified Time: 2021-01-17 09:32:46 +0200 IST
Size: 2 bytes
Human Size: 2 B
Physical Address: local://foo-bucket/4e068d1a46734113abd2218e87aace4c
Checksum: b026324c6904b2a9cb4b88d6d61c81d1
```
(and imagine "Path" in orange).

**Review by nopcoder — APPROVED** [review]
Cool!

**Comment by arielshaqed** [comment]
Thanks! :lizard:

**Comment by itaiad200** [comment]
@arielshaqed Little late to the party, but notice that `.PhysicalAddress` format has more than one option. [Link](https://github.com/treeverse/lakeFS/pull/1204#discussion_r559195804)ing to Oz's explanation on the relavant PR that dealt with it for the API changes that added `PhysicalAddress`.

**Comment by arielshaqed** [comment]
> @arielshaqed Little late to the party, but notice that `.PhysicalAddress` format has more than one option. [Link](https://github.com/treeverse/lakeFS/pull/1204#discussion_r559195804)ing to Oz's explanation on the relavant PR that dealt with it for the API changes that added `PhysicalAddress`.

I read the explanation and I still don't understand.  The API _does_ reformat `PhysicalAddress`, at [this line](https://github.com/treeverse/lakeFS/blob/3d716a89c7351bdc1cca9f7b34845f863b0c179d/api/api_controller.go#L921).  Why would the formatter want to be "smart" and return multiple formats?

**Comment by itaiad200** [comment]
Missed that you use the client and that the `PhysicalAdrress` is already formatted. It does have only one option in this case then.

**Pull request merged**
