### PR TITLE
make authorization errors readable in the UI, change /config to require re fs permissions since it returns storage config

### LINKED ISSUE #2028: (UI) Uninformative errors
Hey- I'm getting uninformative errors when using a LakeFS user without permissions for some action.

for example:
creating a new repository with Developer user - I expected error like UnAuthorized with the specific missing permission 

'Failed to execute 'json' on 'Response' body - stream already read'
image

### PR DESCRIPTION
**Pull request by ozkatz**
Closes #2028

### CODE REVIEW

**Review by guy-har — APPROVED** [review]
LGTM
I Prefer that another reviewer goes over the SQL migrations before you merge

**Comment by ozkatz** [comment]
> LGTM
> I Prefer that another reviewer goes over the SQL migrations before you merge

@guy-har for reference, see https://github.com/treeverse/lakeFS/blob/master/pkg/ddl/000024_actions_auth_policies.up.sql - I use the exact same logic with a different policy.

**Review by nopcoder — APPROVED** [review]
LGTM!

**Comment by ozkatz** [comment]
@arielshaqed see breaking change (`/config` to `/config/storage`)

**Review by arielshaqed — APPROVED** [review]
Cool; thanks!  I shall update #2002 to use `getStorageConfig` and compute the warnings locally.

**Comment by arielshaqed** [comment]
@ozkatz not pulling this because some validation failed.  Instead merging #2002 into this one.

**Pull request merged**
