### PR TITLE
Feature/added scrollto after object is deleted (issue #655)

### PR DESCRIPTION
**Pull request by hi-18-K**
added scrollTo feature. When any object is deleted its scroll position is stored and after it is deleted scrollTo is triggered to restore previous scroll state. 
Uses react scrollTo from "react-scroll" library.
issue #655 

This feature update is working fine in my local environment.
If there is any error, while running , please let me know. 
Also if the code snippet is not placed optimally, please tell me about that too, I was very much confused about that.

---
This change is [Reviewable](https://reviewable.io/reviews/treeverse/lakefs/966)

### CODE REVIEW

**Comment by arielshaqed** [comment]
@nopcoder could you please review?

@hi-18-K please note that JavaScript lint checks failed; I don't think the configured versions like that `constructor()` construct :-/

**Review by nopcoder — CHANGES_REQUESTED** [review]
1. Manage the scroll position is handled by the component and not by our action state.  The component can compare the scroll position state and restore it when the action is done.
2. About the error you see - the code block is not a 'class' so you can't define 'constructor' as part of code execution.

**Comment by hi-18-K** [comment]
okay, got why it happens. I will modify it.

**Comment by hi-18-K** [comment]
sir, please look into the error once again. It is showing some installation requirements. How should we proceed for the same?

**Comment by hi-18-K** [comment]
maybe you will have to update react too for using animation feature from "react-scroll" or we can change it according older version..but it willll not be looking good..

**Comment by nopcoder** [comment]
Closing this one as the current development focus is on architectural changes of the core project.

**Pull request closed without merging**
