### PR TITLE
[spark metadata client] Shade scalapb and bump its version

### LINKED ISSUE #7289: Spark metadata client fails on DataBricks 12.2 LTS
User reporting an issue running the Spark metadata client on DataBricks 12.2 LTS.  Error backtrace includes the line
> ```
> Caused by: java.lang.ClassCastException: com.google.protobuf.timestamp.Timestamp cannot be cast to scalapb.Message
> ```
when deserializing a catalog Entry.  (I can probably furnish more stacktrace lines if needed.)

This prevents them from using the metadata client code.

### PR DESCRIPTION
**Pull request by arielshaqed**
DataBricks Spark versions now load protocol buffers... and the incompatible version broke the lakeFS assembly.  Shade to avoid it... when assembled.  (That might fail to work using `--packages`, but checking that requires a release to Maven Central, sigh).

Fixes #7289.

Will need to test:

* [x] Spark standalone (part of CI)
* [x] DBR 9.x: _tested on 9.1 2023-01-21_.
* [x] DBR 10.x: _tested on 10.4 2023-01-21_.
* [x] DBR 11.x: _tested on 11.3 2023-01-21_.
* [x] DBR 12.x: _tested on 12.2 2023-01-21_.
* [x] DBR 13.x: _tested on 13.2 2023-01-16_.

### CODE REVIEW

**Comment by arielshaqed** [comment]
Current version at s3://treeverse-clients-us-east/lakefs-spark-client/0.13.0-RC.1/lakefs-spark-client-assembly-0.13.0-RC.1.jar works as an assembly, but not as a package on Maven.  Blocking until I can resolve that.

**Comment by itaiad200** [comment]
> Current version at s3://treeverse-clients-us-east/lakefs-spark-client/0.13.0-RC.1/lakefs-spark-client-assembly-0.13.0-RC.1.jar works as an assembly, but not as a package on Maven. Blocking until I can resolve that.

I don't get it. Isn't assembly what we wanted? One can use assembly in Databricks using S3 uri, right?

**Comment by arielshaqed** [comment]
**Reviewers:** Still a draft because I need to confirm that it works for the user, and also 2 more DB releases.  But ready for your reviews!

**Comment by arielshaqed** [comment]
The [assembled JAR from S3](s3://treeverse-clients-us-east/lakefs-spark-client/0.13.0-RC.1/lakefs-spark-client-assembly-0.13.0-RC.1.jar) works everywhere that I tried, and **I would really like to review and pull this**.

**Comment by arielshaqed** [comment]
[+ @guy-har , I'd appreciate it if you have some spare cycles to review!]

**Review by guy-har — APPROVED** [review]
LGTM

**Comment by arielshaqed** [comment]
> > Current version at s3://treeverse-clients-us-east/lakefs-spark-client/0.13.0-RC.1/lakefs-spark-client-assembly-0.13.0-RC.1.jar works as an assembly, but not as a package on Maven. Blocking until I can resolve that.
> 
> I don't get it. Isn't assembly what we wanted? One can use assembly in Databricks using S3 uri, right?

No and yes, respectively.

* **No**: the standard way of using Spark packages is using Maven coordinates for the package in `--packages` or similar on the DataBricks UI or whatever.
* **Yes*: this is a workaround that worked for me on a DB cluster.

Opened more issues to get rid of the need to shade for DB.

**Pull request merged**
