### PR TITLE
Skip metaclient tests in esti

### PR DESCRIPTION
**Pull request by johnnyaug**
These tests already run as part of the _Unit test Spark metadata client_ workflow.

### CODE REVIEW

**Review by arielshaqed — CHANGES_REQUESTED** [review]
I don't like this change: the tested assembly should be the one that we would publish,  if we did publish it.
If anything, I would skip the separate unit test flow for the metadata client. (Or understand what flow sbt expects us to use; I agree the current flow makes little sense)

**Comment by johnnyaug** [comment]
@arielshaqed, Just to clarify - these tests **do** run when we publish the metadata client - here we just package the jar for the GC testing.

**Comment by arielshaqed** [comment]
> @arielshaqed, Just to clarify - these tests **do** run when we publish the metadata client, and also on another workflow - here we just package the jar for the GC testing. I skip them here because it can save some time on Esti testing - which is a bottleneck

Understood, of course.  And I do realize that it takes time.  However removing them makes useful flows fragile: for instance, I can think everything is good (because these tests passed), and then fail to publish at the last moment.

What do you say we instead kill the entire [unit test Spark metadata client](https://github.com/treeverse/lakeFS/blob/10bced0f40f110836e8e2cd2dcbc95b0308c4397/.github/workflows/spark.yaml#L1-L20) flow?

**Review by arielshaqed — APPROVED** [review]
After chatting it over, I'm convinced!  In the worst case we don't notice that the unit test workflow fails, and try to publish, and then need to `git bisect` to determine where the unit test started failing.

Which is **NOT THAT BAD** in exchange for ~ 1m30s less time to test!

**Pull request merged**
