### PR TITLE
docs: enable the links to the publish sdk packages for v1

### PR DESCRIPTION
**Pull request by nopcoder**

### CODE REVIEW

**Review by johnnyaug — APPROVED** [review]
:)

**Review by arielshaqed — APPROVED** [review]
Artifact still no accessible on Maven Central.  But it _is_ accessible by using direct coordinates.

I say we pull and get it over with, it should show up eventually.

**Comment by arielshaqed** [comment]
It's right there on https://mvnrepository.com/artifact/io.lakefs/sdk. Took a few hours longer than expected. ואף-על-פי שיתמהמה, בוא יבוא! And even as it might be delayed, it will surely come...

**Comment by nopcoder** [comment]
Switched to use https://search.maven.org/artifact/io.lakefs/sdk as the previous link returns 403 for the link checker (using HEAD I assume)

**Pull request merged**
