### PR TITLE
Replace repo with commit cache in refManager

### LINKED ISSUE #4618: Commits and Repo cache in refManager should be separate

### PR DESCRIPTION
**Pull request by itaiad200**
closes #4618

### CODE REVIEW

**Review by nopcoder — APPROVED** [review]
Thanks!

**Review by arielshaqed — APPROVED** [review]
1. Thanks!
2. ~Can we make it possible to configure commitCache and repoCache?  I hacked together an image with no commit batching on FindMergeBase these parameters:~
   ```go
   DefaultRepositoryCacheSize   = 20000
   DefaultRepositoryCacheExpiry = 15 * time.Minute
   DefaultRepositoryCacheJitter = DefaultRepositoryCacheExpiry / 20
   ```
   ~With these parameters, p99 for merge was 4.35s, p90 was 475ms (many merges).  I don't think these sizes are necessarily ideal for _all_ users, but we will want them for any _large_ user.  The ref manager code allows for configuration but Graveler setup doesn't have configuration options going all the way into the ref manager.~~
   EDIT: I fixed Grafana to show the wrong thing.  We get p99 29.6s, p90 26s, p50 ~12s.  Still much better than before, and definitely a cause to allow configuration... but not a solution to all difficulties :-(
3. THANKS!

**Comment by itaiad200** [comment]
> 1. Thanks!
> 2. ~Can we make it possible to configure commitCache and repoCache?  I hacked together an image with no commit batching on FindMergeBase these parameters:~
>    ```go
>    DefaultRepositoryCacheSize   = 20000
>    DefaultRepositoryCacheExpiry = 15 * time.Minute
>    DefaultRepositoryCacheJitter = DefaultRepositoryCacheExpiry / 20
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    ~With these parameters, p99 for merge was 4.35s, p90 was 475ms (many merges).  I don't think these sizes are necessarily ideal for _all_ users, but we will want them for any _large_ user.  The ref manager code allows for configuration but Graveler setup doesn't have configuration options going all the way into the ref manager.~
>    EDIT: I fixed Grafana to show the wrong thing.  We get p99 29.6s, p90 26s, p50 ~12s.  Still much better than before, and definitely a cause to allow configuration... but not a solution to all difficulties :-(
> 3. THANKS!

Do you mean CommitsCache defaults perheps? I find it hard to believe that your experiment involves 20k repositories ;)

**Comment by arielshaqed** [comment]
> > 1. Thanks!
> > 2. ~Can we make it possible to configure commitCache and repoCache?  I hacked together an image with no commit batching on FindMergeBase these parameters:~
> >    ```go
> >    DefaultRepositoryCacheSize   = 20000
> >    DefaultRepositoryCacheExpiry = 15 * time.Minute
> >    DefaultRepositoryCacheJitter = DefaultRepositoryCacheExpiry / 20
> >    ```
> >
> >    ~With these parameters, p99 for merge was 4.35s, p90 was 475ms (many merges).  I don't think these sizes are necessarily ideal for _all_ users, but we will want them for any _large_ user.  The ref manager code allows for configuration but Graveler setup doesn't have configuration options going all the way into the ref manager.~
> >    EDIT: I fixed Grafana to show the wrong thing.  We get p99 29.6s, p90 26s, p50 ~12s.  Still much better than before, and definitely a cause to allow configuration... but not a solution to all difficulties :-(
> > 3. THANKS!
> 
> Do you mean CommitsCache defaults perheps? I find it hard to believe that your experiment involves 20k repositories ;)

Nope, I patched the trunk, _without_ your code in this PR.  So everything went into the repo cache.  Obviously now that this is in, I want to be able to configure the commit cache 👼🏽 .

**Pull request merged**
