### PR TITLE
Remove CreateBranch permission check from Import

### LINKED ISSUE #7361: Unnecessary CreateBranch permission check in Import

### PR DESCRIPTION
**Pull request by itaiad200**
closes #7361

### CODE REVIEW

**Comment by itaiad200** [comment]
@N-o-Z why is `fs:CreateBranch` even needed for Import? I don't see a branch is being created at all. Even if it's needed, why should it be so permissive? Currently it's the ability to create any branch in the repo, shouldn't it be the specific branch the Import is trying to create?

**Comment by N-o-Z** [comment]
> @N-o-Z why is `fs:CreateBranch` even needed for Import? I don't see a branch is being created at all. Even if it's needed, why should it be so permissive? Currently it's the ability to create any branch in the repo, shouldn't it be the specific branch the Import is trying to create?

I honestly don't think it's needed anymore. In the past we created an intermediate import branch, today we just use a metarange for the merge.
I think this issue should remove the permission requirement instead of updating the documentation

**Review by N-o-Z — CHANGES_REQUESTED** [review]
I think we need to remove the permission

**Review by N-o-Z — APPROVED** [review]
LGTM!

**Pull request merged**
