### PR TITLE
Stabilize migrate test by using multipart uploads for state file

### LINKED ISSUE #3530: Esti's TestMigrate is flaky
Many failures to PRs with unrelated changes:
1. https://github.com/treeverse/lakeFS/runs/6966413154?check_suite_focus=true
2. https://github.com/treeverse/lakeFS/runs/6955754107?check_suite_focus=true
3. https://github.com/treeverse/lakeFS/runs/6955743858?check_suite_focus=true
4. https://github.com/treeverse/lakeFS/runs/6921763949?check_suite_focus=true

### PR DESCRIPTION
**Pull request by itaiad200**
close #3530

### CODE REVIEW

**Comment by itaiad200** [comment]
Running the CI/CD twice to make sure the flakiness doesn't reoccur.

**Review by N-o-Z — APPROVED** [review]
Looks good, though I'm not sure running it twice is an indication that it solved it.
I guess time will tell

**Review by eden-ohana — COMMENTED** [review]
How does using the multipart upload make the tests more stable?

**Comment by N-o-Z** [comment]
> How does using the multipart upload make the tests more stable?

Instead of streaming a single large file, we'll be sending it in chunks. This lowers the risk of connection reset

**Pull request merged**
