### PR TITLE
Quickstart now uses DuckDB WASM instead of CLI

### LINKED ISSUE #6076: Update Quickstart to use DuckDB WASM so we can remove the DuckDB Docker image
Now that https://github.com/treeverse/lakeFS/pull/6044 is merged, we should be able to update the Quickstart to use DuckDB in the browser alone, and [remove the DuckDB Docker image](https://github.com/treeverse/lakeFS/issues/6001)

### PR DESCRIPTION
**Pull request by rmoff**
- Update Quickstart to use DuckDB WASM
- Updated samplerepo README to use DuckDB WASM

 

### Linked Issue

Closes #6076

---

### Background

See #6076 and #6001

### New Feature

The Quickstart (both docs, and samplerepo) now uses the DuckDB that is integrated in the lakeFS UI for all data manipulation including writing back to lakeFS. Previously this had to be done through the DuckDB CLI which we shipped as a Docker image. #6044 added the necessary functionality to DuckDB-WASM so now we will use it in the quickstart.

### Testing Details

Manually

### CODE REVIEW

**Comment by ozkatz** [comment]
Still in draft, I know but:
1. this looks GREAT and definitely simplifies things
2. the screenshot at the bottom of `commit-and-merge` still uses `LAKEFS_OBJECT()` so should be replaced.
3. One suggestion: except for reverting which is a relatively advanced function, the rest (branching merging and committing) could be done directly in the UI too. Perhaps at some point we want to show tabs (UI, CLI) so that users could try out a simpler way if they are not terminal savvy? (not for this PR obviously)

**Comment by rmoff** [comment]
> * this looks GREAT and definitely simplifies things

Thanks 😄

> * the screenshot at the bottom of `commit-and-merge` still uses `LAKEFS_OBJECT()` so should be replaced.

Fixed (and another one like this too)

> * One suggestion: except for reverting which is a relatively advanced function, the rest (branching merging and committing) could be done directly in the UI too. Perhaps at some point we want to show tabs (UI, CLI) so that users could try out a simpler way if they are not terminal savvy? (not for this PR obviously)

Good idea. Logged #6103

**Comment by rmoff** [comment]
Tested manually against both 0.104.0 (Docker) and build from current `master`. Previous DuckDB gremlins have been vanquished and this PR is good to go.

**Comment by rmoff** [comment]
thanks @arielshaqed -- logged your suggestion and will triage & track :)

**Pull request merged**
