### PR TITLE
Azure: Fix Azure ingest walker

### LINKED ISSUE #5136: Fix Azure ingest walker
Prefix is being redacted and passed to the pager empty

### PR DESCRIPTION
**Pull request by N-o-Z**
Close #5136

### CODE REVIEW

**Comment by nopcoder** [comment]
@N-o-Z can you verify this is a fix - the current test cover the case the base dir can be an empty path.

**Comment by N-o-Z** [comment]
> @N-o-Z can you verify this is a fix - the current test cover the case the base dir can be an empty path.

@nopcoder look at the example of gcs.
What happens is that you are importing the entire container without taking into account the requested prefix (folder).

**Comment by N-o-Z** [comment]
@nopcoder  Added an additional test validation the demonstrates the issue

**Review by nopcoder — APPROVED** [review]
Thanks, I missed this one when aligned the implementaions and added the additional test code.

**Pull request merged**
