### PR TITLE
Replace "i.e." with "e.g."

### PR DESCRIPTION
**Pull request by nishithgadhiya**
Replace "i.e." with "e.g."

### CODE REVIEW

**Review by arielshaqed — APPROVED** [review]
Cool, thanks!

**Comment by arielshaqed** [comment]
Merging once tests pass.

**Review by arielshaqed — CHANGES_REQUESTED** [review]
Sorry, I was wrong.  This misses the intent of the sentence.

See #702, which receives the same comment.  My apologies, the two are so similar I mixed them up.  Closing this one as it arrived second :-(

**Comment by nishithgadhiya** [comment]
@arielshaqed  No Problem I will find another
Thanks

**Pull request closed without merging**
