### PR TITLE
Support assuming a role (only on Hadoop 3)

### PR DESCRIPTION
**Pull request by arielshaqed**
# Reviewers please read!

I have tried to split this PR up into manageable commits.  You might review each commit separately, and it should make more sense:
* 027fb8ea6b1d7f3bacd63aa9a49ecb0b4cdb6648 is (just!) a facility for conditional compilation of code, allowing us to compile different files for Hadoop 2 and Hadoop 3 "flavours".
* 0a87e65f6f2503ce62e49789f326dda494b5e589 refactors `getS3Client` out of GarbageCollector.scala, once for each flavour.

Good luck!

### CODE REVIEW

**Review by talSofer — APPROVED** [review]
WOW! for the clean solution and for mastering sbt!

WDYT of chaining the hadoop version into the jar name as we do with Spark and Scala versions?

**Comment by arielshaqed** [comment]
> WOW! for the clean solution and for mastering sbt!

Not sure about "clean"; macro based solutions similar to `#ifdef` would be easier for me to read, but macros are still not entirely in Scala, and I was worried about having to work with differences between Scala 2.11 and 2.12.

Also wasn't sure Scala macros would actually do the job.

> WDYT of chaining the hadoop version into the jar name as we do with Spark and Scala versions?

Good idea!  Will do...

**Comment by arielshaqed** [comment]
Thanks!  Pulling...

**Review by arielshaqed — COMMENTED** [review]
Sorry, forgot to post this comment before pulling :-(

**Pull request merged**
