### PR TITLE
Strings in configuration that contain only digits are parsed incorrectly #3253

### LINKED ISSUE #3253: Strings in configuration that contain only digits are parsed incorrectly
# What

If a string in the YAML file contains only digits, it is parsed first as a number (by the YAML parses, _according to the rules of that language_) and then converted to a string (by `mapstructure`, which `viper` sets up to perform weak typing).  As a result any leading zeroes are stripped.  So when a user uses a value like
```yaml
must_be_a_string: 01234
```
in a config file, the YAML parser sees that it has only digits so it parses it as  the number 1234, and then viper asks mapstructure to convert it back to the string "1234".  This is incorrect :-/

Similar things will probably happen with other implicitly-typed strings, including possibly `TRUE` and `yes` (which will be parsed as the string "1" due to an implicit boolean conversion).

## This really happens!

For example, in #2996 config parsing broke down for a string value whose values contained just digits in the YAML file.  [The fix there](#3252) was to use a new "only string" type that refuses implicit conversions from non-string values.  So "yes" is _still_ parsed as a true (1) value, but then config parsing errors out

```
* error decoding 'Metastore.Glue.catalog_id': must be a string, not a bool
```

instead of parsing a "1" (!!!) catalog ID.

## Workaround

If this happens, _quote_ the string.  Now YAML will know it's a string.

# Possible solutions

This happens because viper calls mapstructure with weak typing enabled.  Unfortunately weak typing handles _many_ conversions, most of them useful.  So we have at least these alternatives (_not_ in order of preference):

* Use `OnlyString` in all config structures instead of `string`.  This still lets us make a mistake whenever we add a new field!
  + Add some build-time enforcement to prevent `string` in config structures.
* Turn off viper requesting weak typing from mapstructure, and explicitly add the desired decoder hooks back in.  This may be harder than it sounds, as mapstructure appears to special-case weak typing (so there might not be all the desired decoding hooks!).
  + Look for a viper fork or a mapstructure fork that we could use, that allow more granularity in disabling weak typing.  This might also help with [this comment](https://github.com/treeverse/lakeFS/pull/1734#issuecomment-1107519049) about issues in the trunk version of viper.

### PR DESCRIPTION
**Pull request by johnmantios**
### Linked Issue

Tackles #3253 

---

### Background

Out of all the options discussed in issue 3253, this is the first one proposed by @arielshaqed. 

### Testing Details

No unit tests were written. Codebase compiles. 

### Breaking Change?

No breaking change AFAIK

---

### Contact Details

lakeFS slack

### CODE REVIEW

**Review by arielshaqed — APPROVED** [review]
Neat!

A much larger change is to do the same thing _on `pkg/config/config.go_`.  This PR is great as it definitely improves the code!  And more users use `lakectl` than `lakefs`, so configuration improvements there are obviously better.  So I intend to keep the issue open -- and scope it down to just lakefs -- even after pulling this.

**Comment by arielshaqed** [comment]
For changelog:
* Verify strings in configuration are not numbers (which will lose leading zeroes).

**Review by arielshaqed — CHANGES_REQUESTED** [review]
Single [error](https://github.com/treeverse/lakeFS/actions/runs/4396638042/jobs/7699874329) remains:
```
Error: cmd/lakectl/cmd/log.go:57:4: cannot use cfg.Values.Server.EndpointURL (variable of type "github.com/treeverse/lakefs/pkg/config".OnlyString) as type string in argument to strings.TrimSuffix
```
Let's fix and we can pull!

**Review by arielshaqed — COMMENTED** [review]
-

**Comment by itaiad200** [comment]
Thank you for your contribution @johnmantios , implemented similarly in #6382

**Pull request closed without merging**
