### PR TITLE
Optionally set mtime in linkPhysicalAddress

### LINKED ISSUE #8337: Allow setting mtime in linkPhysicalAddress
Intended use: allow lakeFSFS to link objects with the same CreationDate as their backing objects.

stageObject flow _does_ allow setting an mtime, so this does not introduce a new vector for generating bad object metadata.  I do not believe that being able to do this must be controlled by a config value.

### PR DESCRIPTION
**Pull request by arielshaqed**
Closes #8337.  Will be used in #8339.

### CODE REVIEW

**Comment by arielshaqed** [comment]
Will submit with approval from any reviewer unless otherwise requested.

**Review by itaigilo — COMMENTED** [review]
The fix itself LGTM - 
Though I don't have enough context about what it's trying to solve.

Following here.

**Review by N-o-Z — APPROVED** [review]
LGTM!
I assume there's a follow up issue for LakeFSFS?

**Comment by arielshaqed** [comment]
> LGTM! I assume there's a follow up issue for LakeFSFS?

Thanks!  Yup, forgot to link to #8339.

**Pull request merged**
