### PR TITLE
Add a deprecation notice for the legacy Python client

### PR DESCRIPTION
**Pull request by arielshaqed**
We can point at this in announcements and if users ask questions that it covers.

Previously #8195 changed the description of the Python client.  I intentionally do _not_ want a link from the PyPI description to here: that description should be terse and say in one sentence what is the package and why you should not use it.

### CODE REVIEW

**Comment by arielshaqed** [comment]
We do not need to make as much noise for Java: it has been labelled "lakeFS OpenAPI Java client legacy SDK" since before 1.0, people know.

**Comment by arielshaqed** [comment]
- Happy to merge this elsewhere, just say where!
- Feel free to merge if you like & don't want to move it.

**Review by N-o-Z — APPROVED** [review]
LGTM!

**Review by ozkatz — APPROVED** [review]
LGTM! very clear.

**Comment by arielshaqed** [comment]
Thanks!

**Pull request merged**
