### PR TITLE
Changes python example from lakefs_client to lakefs_sdk

### LINKED ISSUE #6828: [Bug]: Documentation bug - lakeFS Client
### What happened?

The current documentation examples use lakefs_client even thought it is deprecated and we recommend using lakefs_sdk.

### Expected behavior

_No response_

### lakeFS version

_No response_

### How lakeFS is installed

_No response_

### Affected clients

_No response_

### Relevant log output

_No response_

### Contact details

_No response_

### PR DESCRIPTION
**Pull request by iddoavn**
Closes #6828 

## Change Description
Changed the documentation example for python integration to use lakefs_sdk instead of lakefs_client

### CODE REVIEW

**Review by ozkatz — CHANGES_REQUESTED** [review]
Overall looks great! the `upload_object` might be wrong or just confusing. Other than that - LGTM!

**Comment by nopcoder** [comment]
Suggest alternative https://github.com/treeverse/lakeFS/pull/6830

**Review by nopcoder — CHANGES_REQUESTED** [review]
Posted my draft as PR https://github.com/treeverse/lakeFS/pull/6830 - feel free to update/comment.

**Comment by nopcoder** [comment]
Docs updated by the above PR - closing.
In case something is missing please re-open and rebase.

**Pull request closed without merging**
