### PR TITLE
Use pgx driver defaults in migration

### LINKED ISSUE #2302: Remove default value for db_connection_string
It is hardly usable, and it masks away errors when the config isn't loaded properly.
Better to exit if that value is missing, instead of returning a connection error which isn't always very indicative to the fact that there's no db running in the other end.

### PR DESCRIPTION
**Pull request by arielshaqed**
golang-migrate has a subtly different default: it relies on a database name
inside the DB connection URL.  Explicitly create migration database.Driver,
to allow using the empty default value.

Fixes #2302.

### CODE REVIEW

**Review by nopcoder — DISMISSED** [review]
Simple - like!

**Comment by arielshaqed** [comment]
Doesn't actually migrate with an empty connection string, sorry.  Dismissing review, will explicitly request another review when it appears actually to work :shrug:.

**Comment by arielshaqed** [comment]
Actually sorry, it _does_ work.  Tested by removing the connection_string from my config, and then running with
```ini
    PGUSER=lakefs
    PGPASSWORD=lakefs
```

Works for both `migrate` and `run`.

Please see that the above test convinces you, and if so -- please reapprove.

**Review by nopcoder — APPROVED** [review]
Still thinks its doing good

**Comment by arielshaqed** [comment]
Thanks -- and sorry for the runaround!

**Pull request merged**
