### PR TITLE
Report statistics for commit metadata button clicks

### LINKED ISSUE #7174: [BI] Collect stats for (Airflow) metadata button clicks in the UI
When a user clicks a MetadataUIButton in the webui, report stats of the URL
type.

### PR DESCRIPTION
**Pull request by arielshaqed**
Will reflect e.g. Airflow integration.

Tested manually by examining requests when clicking on sample.

Fixes #7174.

### CODE REVIEW

**Comment by arielshaqed** [comment]
Picked 2 possibly-available reviewers but will pull if even one of you approves -- let me know if you'd rather I waited for both!

**Review by N-o-Z — COMMENTED** [review]
Thanks @arielshaqed 
I went through the issue and PR and couldn't quite understand the full context.
How is adding this statistics relate to airflow?
Why do we want to collect these statistics?

**Comment by arielshaqed** [comment]
Great questions, thanks!

> Thanks @arielshaqed I went through the issue and PR and couldn't quite understand the full context. How is adding this statistics relate to airflow?

These buttons are generated mostly by the lakeFS Airflow provider when it generates commits and merges.  In that case they link the commit back to the Airflow task.

> Why do we want to collect these statistics?

We are interested in seeing whether these links are actually useful.  (That might be a signal to add more such integrations!)

**Review by guy-har — APPROVED** [review]
LGTM

**Comment by arielshaqed** [comment]
>  Please note that lakectl local also uses the button integration

Bettterer and betterer!

**Pull request merged**
