### PR TITLE
re-org lakectl cmd

### PR DESCRIPTION
**Pull request by nopcoder**
- flat each command to a file
- use Must as generic function
- simplify common helpers

### CODE REVIEW

**Review by johnnyaug — APPROVED** [review]
I think this one would be better off if it was split into 2 PRs: one to break the commands to separate files, and the second one for the other refactors. This way it's hard to review. That being said, LGTM.

**Review by N-o-Z — CHANGES_REQUESTED** [review]
Could not go over the entire PR changes but I have 2 main points:
1. Maybe it's better to split this PR into several per command (I think it will be much faster to review that way)
2. This create additional files in the root package and IMO adds to the clutter. My initial suggestion was to create a package per sub command, which will make this much more readable.

**Comment by nopcoder** [comment]
Splitting each command into a file with associated code should help manage the code and simplify navigation. It starts by mapping the helpers and moving them into common_helpers.go. After having each command in a file and helpers in one location - map common code and private helpers. Now there are three main helpers left: a Must function that parses flag values, prompt yes/no and OpenByPath.

I think we can move and use them for both lakeFS and lakeCTL cmd packages - which I planned for a different PR.

Just didn't want to make hierarchy of packages under cmd package.

**Comment by nopcoder** [comment]
reimplemented at https://github.com/treeverse/lakeFS/pull/6260

**Pull request closed without merging**
