### PR TITLE
Allow OIDC as default login

### PR DESCRIPTION
**Pull request by johnnyaug**
Configure lakeFS to redirect to OIDC login automatically.

### CODE REVIEW

**Review by arielshaqed — APPROVED** [review]
NEAT!

If OIDC default is set, (how?) can a user still use username+password to login?  And, will it make sense to keep a cookie on the browser for how to try logging in the next time?

**Comment by johnnyaug** [comment]
@arielshaqed - your comment is very important. I changed it so that if you explicitly browse to "/auth/login" you get the old, internal login. If you are redirected from another page - we redirect to OIDC login. PTAL.

**Comment by arielshaqed** [comment]
> @arielshaqed - your comment is very important. I changed it so that if you explicitly browse to "/auth/login" you get the old, internal login. If you are redirected from another page - we redirect to OIDC login. PTAL.

Still looks great!  If I want to use username+password then I have to type in `.../auth/login`, or is there some link on the OIDC login page that I can use?

**Comment by johnnyaug** [comment]
@arielshaqed, thanks! The OIDC page is at the control of the external provider - the user may choose to add a link there to "/auth/login".

**Pull request merged**
