### PR TITLE
Added missing field `generation` to dumps

### PR DESCRIPTION
**Pull request by idanovo**
Added missing field `generation` to our commits dumps

### CODE REVIEW

**Comment by johnnyaug** [comment]
Awesome work! Please add a description to the PR 
(the person who publishes the next release may use it for the Changelog)

**Review by johnnyaug — APPROVED** [review]

**Review by itai-david — APPROVED** [review]
LGTM

**Comment by talSofer** [comment]
> Please add a description to the PR (the person who publishes the next release may use it for the Changelog)

I second this :) @idanovo can you please add more to the pr description explaining the generation field usage and how you change impacts our users (help us reproduce issues they run into).

**Comment by idanovo** [comment]
> > Please add a description to the PR (the person who publishes the next release may use it for the Changelog)
> 
> I second this :) @idanovo can you please add more to the pr description explaining the generation field usage and how you change impacts our users (help us reproduce issues they run into).

Changed the description, WDYT?

**Pull request merged**
