### PR TITLE
[#528] fix misleading error when trying requesting for brnaches on non-existing repository

### PR DESCRIPTION
**Pull request by sarathsp06**
[#528] fix misleading error when trying requesting for brnaches on non-existing repo

### CODE REVIEW

**Comment by guy-har** [comment]
@sarathsp06 looks good, 
Thanks.
one small request, there was a mistake in the example in the issue.
can you please change `repo` to `repository`.

**Comment by sarathsp06** [comment]
@guy-har made changes as suggested

**Review by guy-har — APPROVED** [review]
👍

**Comment by guy-har** [comment]
@sarathsp06 approved and merged.
Thanks for contributing!

**Pull request merged**
