### PR TITLE
Docs: Removing backslashes from examples to better support Windows users

### LINKED ISSUE #7946: [Bug]: Quickstart commands work on Linux but return syntax errors on Windows PowerShell
### What happened?

The quickstart commands provided in the documentation work as expected on Linux. However, when running the same commands on Windows PowerShell, several syntax errors occur.
        
Steps to Reproduce:
1. Open Quickstart
2. Paste first line onto PowerShell

Current fix is to replace \ with ` (backtick) if using Windows PS. Should work for both standard. 

### Expected behavior

lakeFS bootup and functionality should not differ between Linux and Windows cmd lines. 

### lakeFS version

1.28.0

### How lakeFS is installed

local

### Affected clients

_No response_

### Relevant log output

```shell
PS C:\Users\omert> docker run --name lakefs --pull always \
docker: invalid reference format.
See 'docker run --help'.
PS C:\Users\omert> --rm --publish 8000:8000 \
At line:1 char:3
+ --rm --publish 8000:8000 \
+   ~
Missing expression after unary operator '--'.
At line:1 char:3
+ --rm --publish 8000:8000 \
+   ~~
Unexpected token 'rm' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

PS C:\Users\omert>              treeverse/lakefs:latest \
treeverse/lakefs:latest : The term 'treeverse/lakefs:latest' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At line:1 char:14
+              treeverse/lakefs:latest \
+              ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (treeverse/lakefs:latest:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\omert>              run --quickstart
run : The term 'run' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:14
+              run --quickstart
+              ~~~
    + CategoryInfo          : ObjectNotFound: (run:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Suggestion [3,General]: The command run was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\run". See "get-help about_Command_Precedence" for more details.
PS C:\Users\omert>
```

### Contact details

omer.tzioni@treeverse.io

### PR DESCRIPTION
**Pull request by omertzionitreeverse**
Closes #7946
## Change Description
Removed Unix new line characters to support both Unix and Windows
### Background
Following best practices as observed in Docker Postgres(https://hub.docker.com/_/postgres), MongoDB(https://www.mongodb.com/resources/products/compatibilities/docker), and Elastic(https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html). 

### Bug Fix

Removed new line characters throughout quickstart. 
      
### Testing Details

Ran through Windows PowerShell, deleted Unix newline whenever an error came up.

### CODE REVIEW

**Review by arielshaqed — COMMENTED** [review]
Firstly, I believe that the pr title is misleading: it does not remove new lines, and these are not AFAIK Unix characters. IIUC this pr removes backslashes from sample commandlines. 

Not my decision, but I believe that this change makes for less readable documentation. If we wish to support Windows CMD, and possibly PowerShell, we should do do explicitly by adding tabs for that.

**Review by iddoavn — APPROVED** [review]
Made one change and tested everything.

**Comment by iddoavn** [comment]
> Firstly, I believe that the pr title is misleading: it does not remove new lines, and these are not AFAIK Unix characters. IIUC this pr removes backslashes from sample commandlines.
> 
> Not my decision, but I believe that this change makes for less readable documentation. If we wish to support Windows CMD, and possibly PowerShell, we should do do explicitly by adding tabs for that.

Thanks @arielshaqed - In the examples above they all ended up using longer lines as opposed to 2 versions for different OSs.

**Comment by itaiad200** [comment]
@omertzionitreeverse could you rebase on top of `origin/master` and push? I want to see the docs preview run but I believe it was fixed since you forked out

**Comment by omertzionitreeverse** [comment]
> @omertzionitreeverse could you rebase on top of `origin/master` and push? I want to see the docs preview run but I believe it was fixed since you forked out

I looked online on how to do just that, and gave it a go. Let me know if I successfully fixed what you wanted me to.

**Comment by itaiad200** [comment]
> > @omertzionitreeverse could you rebase on top of `origin/master` and push? I want to see the docs preview run but I believe it was fixed since you forked out
> 
> I looked online on how to do just that, and gave it a go. Let me know if I successfully fixed what you wanted me to.

Sorry my bad, the reason the preview isn't available is that a fork PR cannot read its secret token, by design. I created another PR for the preview and the longest line looks like this. I'm approving because I believe this is an improvement for Windows users.
image

**Review by itaiad200 — APPROVED** [review]

**Pull request merged**
