### PR TITLE
Remove all fork related secrets workflow logic

### PR DESCRIPTION
**Pull request by itaiad200**

### CODE REVIEW

**Review by arielshaqed — APPROVED** [review]
Thanks!

**Comment by arielshaqed** [comment]
Note that at least this one wanted a manual security check.  I just triggered it manually.

**Comment by arielshaqed** [comment]
We're not going to do this right now?  (Still approved, just asking to know.)

**Comment by itaiad200** [comment]
> We're not going to do this right now? (Still approved, just asking to know.)

Yes, it's not feasible. When you trigger it you run it on the source branch. That source branch differs from the reference passed here (which is `pulls/666/merge`). You can look for the check to pass on the branch itself, but it is less secure (imagine approving a branch, then someone adds a malicious code after you ran the sec-check). Also - source branch will not be available for us from forked repos.

**Pull request merged**
