### PR TITLE
Add example message in `lakectl repo create` command

### LINKED ISSUE #2467: Improve usage message in lakectl repo create
The command to create a new repository from lakectl is: 
`lakectl repo create <repository uri> <storage namespace>`

However, it is not fully clear what is the repository uri, and the help flag doesn't explain it.
image

If a user tries to create a repository and specifies only the name (not the full uri) he gets a "malformed lakefs uri" error:
image

We should add to the repository help flag an explanation on how the uri should look. 
for example:
example repository uri: "lakefs://some-repo-name"

### PR DESCRIPTION
**Pull request by mishraprafful**
**Related PR**
Closes #2467 

**Changes**
* Added an example for `lakectl repo create` command

### CODE REVIEW

**Review by nopcoder — CHANGES_REQUESTED** [review]
Thanks for the contribution - minor comments for final approval. Please review the suggestions.

**Comment by mishraprafful** [comment]
@nopcoder Thanks for the suggestions, I have made the suggested changes. Please consider for re-review.

**Review by nopcoder — APPROVED** [review]
Looks good, thank!

**Comment by mishraprafful** [comment]
@nopcoder is the validation check failing an issue? I think the gofmt check passes.

**Comment by nopcoder** [comment]
@mishraprafful very sorry - should have spot it in the review stage. The lakectl documentation is auto-generated, so running `make gen-docs` should update the required file and you can it to this PR.

**Pull request merged**
