### PR TITLE
Added instructions to update the container ssl certificates

### LINKED ISSUE #4176: Update the container ssl certificates
How to configure HTTPS endpoint for Docker installation?

### PR DESCRIPTION
**Pull request by kesarwam**
Added instructions for Docker installation to configure HTTPS endpoint for lakeFS.

Fix #4176

### CODE REVIEW

**Review by nopcoder — CHANGES_REQUESTED** [review]
The documentation is talking about update the container ssl certificates - not https endpoints for lakefs.

**Review by nopcoder — CHANGES_REQUESTED** [review]
Our lakeFS Docker image build already holds a step to update the root certificates. There is no need to instruct users to manually update the image this way. The proper way is to build a new image with the updated certificates.
Don't think we need these instructions as part of our documentation.
Also, the associated issue is talking about https and not ssl certificates.

**Review by iddoavn — APPROVED** [review]

**Comment by kesarwam** [comment]
> Our lakeFS Docker image build already holds a step to update the root certificates. There is no need to instruct users to manually update the image this way. The proper way is to build a new image with the updated certificates. Don't think we need these instructions as part of our documentation. Also, the associated issue is talking about https and not ssl certificates.

@nopcoder Recently a customer reported following error and Tal gave them following instructions to resolve this issue. Tal told that these instructions were provided by you. @iddoavn (Iddo) asked me to document this. I am not familiar with this issue or solution. So, if I am not documenting it correctly then can you please document it so if any other customer face the same problem then they know the solution:

**ERROR**:
time="2022-09-05T10:17:00Z" level=error msg="failed to get region for bucket, falling back to default region" func="pkg/block/s3.(*ClientCache).getBucketRegion" file="build/pkg/block/s3/client_cache.go:71" error="RequestError: send request failed\ncaused by: x509: certificate signed by unknown authority" host="x.x.x.x:8000" log_audit=API method=POST path=/api/v1/repositories request_id=258fa211-99fe-4d7f-bd07-4c22bc2c8efd service_name=rest_api
time="2022-09-05T10:17:02Z" level=error msg="failed to get S3 object bucket iceberg key dummy" func="pkg/logging.(*logrusEntryWrapper).Errorf" file="build/pkg/logging/logger.go:258" error="RequestError: send request failed\ncaused by: Get \"ECS-endpoint:443/bucket-name/dummy\": x509: certificate signed by unknown authority" host="x.x.x.x:8000" log_audit=API method=POST operation=GetObject path=/api/v1/repositories request_id=258fa211-99fe-4d7f-bd07-4c22bc2c8efd service_name=rest_api
time="2022-09-05T10:17:02Z" level=warning msg="Could not access storage namespace" func="pkg/api.(*Controller).CreateRepository" file="build/pkg/api/controller.go:1297" error="RequestError: send request failed\ncaused by: Get \"ECS-endpoint:443/bucket-name/dummy\": x509: certificate signed by unknown authority" reason=unknown service=api_gateway storage_namespace="s3://iceberg/"

**Solution provided by you**
# copy you certificate from the machine to the container 
docker cp $PATH_TO_CERT_ON_YOUR_MACHINE 94931994934a:/usr/local/share/ca-certificates/

# update certificates inside the containers
docker exec 94931994934a -it bash 
apk update && apk add ca-certificates

# restart lakeFS
docker stop 94931994934a
docker start 94931994934a

**Comment by nopcoder** [comment]
1. The user had a custom certificate and the above will not help for this one.
2. I've updated the issue and the docker to include updates certificates. 
3. Do not need to document a temporary workaround.

**Comment by iddoavn** [comment]
@nopcoder 
Can you please point me to where in our documentation a user facing this issue should go to find out how to add the certificate?

**Comment by nopcoder** [comment]
The issue was how to update the certificates in the lakefs container.  We added the instructions to the build process 
Are you asking about how to support a custom/user created certificate?

**Comment by iddoavn** [comment]
My Mistake - I looked on the wrong issue. Thanks for the quick response.

**Pull request closed without merging**
