### PR TITLE
solved #501 issue

### PR DESCRIPTION
**Pull request by ShyamPraveenSingh**
Changed "access_secret_key" to "secret_access_key"

### CODE REVIEW

**Comment by ShyamPraveenSingh** [comment]
Hi, I have solved an issue #501. Can you please review and merge it.

**Comment by arielshaqed** [comment]
As mentioned on the issue you mention, dupe of #648.

Thanks!  Note that we have plenty of open unassigned issues; do let us know on our Slack channel if you need help finding an open issue you could work on.

**Comment by ShyamPraveenSingh** [comment]
Sorry I did not understand what mistake I made.
Can you please explain it to me?

**Comment by arielshaqed** [comment]
> Sorry I did not understand what mistake I made.
> Can you please explain it to me?

Sure, sorry for being too brief.  There is already another PR, #648, that is virtually identical to this PR.  If you look at #501, it is assigned to another contributor.  It's usually a good idea to head over to the issue, verify that it is unassigned and that nobody has asked for it, and then to request that we it to you.  If two PRs are identical then we cannot do any better than prefer the earlier one.

Sorry.

**Pull request closed without merging**
