### PR TITLE
Add Java (and Scala...) API client

### PR DESCRIPTION
**Pull request by arielshaqed**
None of the Scala generators appear to manage to generate code for an OpenAPI file that uses words such as "path", so going for a Java-based solution instead.

Works with Scala!!1!  E.g. in the REPL (with appropriately-set classpath; `mvn dependency:build-classpath` helped):
```scala
scala> val c = new ApiClient
val c: io.treeverse.lakefs.clients.api.ApiClient = io.treeverse.lakefs.clients.api.ApiClient@160a5e87

scala> c.setUsername("...")
scala> c.setPassword("...")

scala> val ra = new RepositoriesApi(c)
val ra: io.treeverse.lakefs.clients.api.RepositoriesApi = io.treeverse.lakefs.clients.api.RepositoriesApi@6c540ca5

scala> c.setBasePath("http://localhost:8000/api/v1")
val res25: io.treeverse.lakefs.clients.api.ApiClient = io.treeverse.lakefs.clients.api.ApiClient@160a5e87

scala> ra.getRepository("moo")
val res28: io.treeverse.lakefs.clients.api.model.Repository =
class Repository {
    id: moo
    creationDate: 1618297711
    defaultBranch: main
    storageNamespace: s3://treeverse-ariels-test/repos/direct/moo
}
```

### CODE REVIEW

**Comment by arielshaqed** [comment]
Part of #1806 .

**Review by johnnyaug — APPROVED** [review]

**Review by johnnyaug — COMMENTED** [review]
Suggestion: 
The Maven group can be "io.treeverse.lakefs", and the artifact name "api-client".
We can then open an issue to also change the Spark client to conform to this grouping.

**Comment by arielshaqed** [comment]
> Suggestion:
> The Maven group can be "io.treeverse.lakefs", and the artifact name "api-client".
> We can then open an issue to also change the Spark client to conform to this grouping.

Good idea.  Done!

**Review by johnnyaug — APPROVED** [review]

**Comment by arielshaqed** [comment]
Thanks for patience and very useful suggestions!  Pulling..

**Review by talSofer — APPROVED** [review]

**Pull request merged**
