### PR TITLE
Directly include Swagger API ref in docs

### LINKED ISSUE #793: Reference page having height issues
On the API reference page, when collapsing the sections (setup, auth, etc) the height of the page remains the same when the sections are expanded and thus having a big empty space between the footer and the main content.

image

Click on the arrows for collapsing the section.

Go to the bottom of the page and see the effect (the empty space)

### PR DESCRIPTION
**Pull request by arielshaqed**
Fixes #793 .

### CODE REVIEW

**Comment by arielshaqed** [comment]
@ozkatz not sure how best to test this.  Thinking we might just push it and roll back if it's horrid :-/

**Comment by ozkatz** [comment]
Oops.

**Comment by itaiad200** [comment]
> @ozkatz not sure how best to test this. Thinking we might just push it and roll back if it's horrid :-/

`make docs-serve` won't work?

**Comment by arielshaqed** [comment]
Confirmed still _not_ to work using `make docs-serve`.  Back to the drawing board :triangular_ruler: :straight_ruler:

**Comment by arielshaqed** [comment]
Thanks!  This works.

**Review by ozkatz — APPROVED** [review]

**Pull request merged**
