### PR TITLE
Remove UpdateBranchToken API

### LINKED ISSUE #5874: Import: Deprecate plumbing API
Need to decide whether we want to keep or remove the following plumbing API:

- IngestRange
- CreateMetaRange
- UpdateToken

and deprecate if we decide to remove them

### LINKED ISSUE #6524: API cleanup: updateBranchToken
Remove the use of UpdateBranchToken API.

Part of https://github.com/treeverse/lakeFS/issues/5874

### PR DESCRIPTION
**Pull request by nopcoder**
Close #5874
Close #6524

### CODE REVIEW

**Review by arielshaqed — APPROVED** [review]
Thanks!  Good riddance, I guess.

Can't remember why we ever had it; I guess for one of the import implementations?  We might need something like this for when we write `lakectl stash`, but it won't be this one and **definitely** not until we know what we need.

**Comment by nopcoder** [comment]
Still not merging this one - import test on azure fails without calling upgrade branch token

**Review by itaiad200 — CHANGES_REQUESTED** [review]
Not seeing [this](https://github.com/treeverse/lakeFS/blob/c83ef83bf67e707d9d206ca506f1ea4101910cf0/webui/src/lib/api/index.js#L543) deleted and just making sure no flow breaks

**Comment by nopcoder** [comment]
> Not seeing [this](https://github.com/treeverse/lakeFS/blob/c83ef83bf67e707d9d206ca506f1ea4101910cf0/webui/src/lib/api/index.js#L543) deleted and just making sure no flow breaks

Thanks, blocked from merge this change as it looks like Azure ingest flow depends on this logic.
The code you referenced is not in used and we can remove it from the webui.
I was thinking on removing all the ingest API but I wasn't sure if there is still code that would like to use it.

**Pull request merged**
