### PR TITLE
Fix - merge direction #955

### PR DESCRIPTION
**Pull request by shamikakumar**
Implemented #955

### CODE REVIEW

**Comment by itaiad200** [comment]
@shamikakumar Thanks for your effort!
Notice the direction of the arrow is opposite to the direction of the merge.
You can switch the arrow direction, however it makes more sense if you could simply switch the labels between the base branch and the target branch. e.g. merge to `master` should have `master` on the left, arrow pointing left, and the feature branch on the right.

**Review by itaiad200 — CHANGES_REQUESTED** [review]
Should switch branches so that merge direction matches.

**Comment by shamikakumar** [comment]
@itaiad200 oh, my bad. I see now how that's confusing, since we're used to the GitHub convention.

**Comment by itaiad200** [comment]
Hey @shamikakumar 
You're absolutely right about keeping Github's convention! 

I still see the merge direction the other way around:
image

The scenario: created `feature-1` branch from `master`, added a single file to `feature-1` branch and committed. When I'm comparing I should get the above results when `master` is on the left (base branch) and `feature-1` branch is on the right. You can also use the description in the Merge button for the direction. 

Let me know if you have any further questions, I think we're almost there :)

**Comment by shamikakumar** [comment]
@itaiad200 could you check now ? I think you may be viewing my previous commit

**Comment by itaiad200** [comment]
LGTM
Thanks for your help @shamikakumar !

**Review by itaiad200 — APPROVED** [review]

**Pull request merged**
