### PR TITLE
Run OpenAPI docker image as user

### PR DESCRIPTION
**Pull request by arielshaqed**

### CODE REVIEW

**Review by nopcoder — APPROVED** [review]
LGTM!

**Comment by arielshaqed** [comment]
Tested using the "It Worked On My Machine" methodology.

@nopcoder please try it on your MacOS box.  Then, if you approve, before pulling I shall also change the other `docker run`s.

**Comment by arielshaqed** [comment]
@nopcoder PTAL and also verify it works on macOS (because Docker and macOS and Darwin and Linux and Ubuntu and Debian).

**Comment by nopcoder** [comment]
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/.local'
Check the permissions.

**Comment by arielshaqed** [comment]
> ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/.local'
> Check the permissions.

PTAL; 42c3e52 should fix this.

**Review by nopcoder — APPROVED** [review]
works for me!

**Comment by arielshaqed** [comment]
Thanks; pulling!

**Pull request merged**
