### PR TITLE
Add videos to docs

### LINKED ISSUE #7792: Would be good to also be able to consume instructions using videos
We have a lot of videos out there already describing usage and integration of lakeFS. 
Some individuals prefer to consume videos as they learn software. 
Would be good to sprinkle those into the docs where relevant.

### PR DESCRIPTION
**Pull request by iddoavn**
Closes #7792 

## Change Description

Added links to YouTube where relevant for some videos to help understand lakeFS. 

### Background

Share context and relevant information for the PR: offline discussions, considerations, design decisions etc.

Since I'm not sure how easy it will be to track the videos (although I assume it will be simple with the YouTube admin) I've added a [doc containing the current views of the videos today](https://docs.google.com/spreadsheets/d/1ej29QVBdlu8hxv3lk62pXE5_DyL3vL-ar1xQmOwSyQg/edit?usp=sharing) - so we can compare down the line. 
      
### New Feature

We have a lot of videos out there already describing usage and integration of lakeFS.
Some individuals prefer to consume videos as they learn software.
Would be good to sprinkle those into the docs where relevant.

### CODE REVIEW

**Review by N-o-Z — CHANGES_REQUESTED** [review]
Great addition!
I think there's some design improvements that can be done for the embedding.
I would probably look better centred and perhaps with some border or shading. 
@eladlachmi you might want to have a look as well

**Comment by iddoavn** [comment]
It was actually centered, and then I moved it back to the side because I think it looks better on the left :)

**Review by ozkatz — APPROVED** [review]
Great!

**Comment by N-o-Z** [comment]
> It was actually centered, and then I moved it back to the side because I thought it looked better on the left :) - That's my personal opinion of course.
> 
> Nevertheless - Happy to make any specific adjustments you or @eladlachmi think are better, I'm not considering myself an expert on this.

Removing myself from the review. I think we could improve the design but as you said I'm no expert as well. Maybe @eladlachmi or Tamar can take a look at this

**Pull request merged**
