### PR TITLE
Remove Repositories from ACL in UI

### LINKED ISSUE #5689: Remove ACL repository scoping
## Goal
Remove ACL repository scoping

## Why
ACL by design is a set of permissions associated with a specific system object, in our case, a group.
The repository scoping adds complexity both to the migration and to the different interfaces due to its nature of not being a classic ACL implementation.
Removing the repository scoping will make the ACL implementation in lakeFS a classic one.

On top of that, the initial requirement we heard from the community, which drove us to add the repository scoping, is irrelevant as once we've released this feature, we got the feedback that it'll be useless for them without making more changes, which essentially means bringing RBAC back.
Therefore, for the sack of simplicity of this feature, we'd like to remove the ACL scoping.

## Why Now
Due to the fact the RBAC -> ACL requires migration, and we'd like the community to have a minimal impact migrating between the versions, this needs to be released as soon as possible to avoid unnecessary migrations.

### PR DESCRIPTION
**Pull request by guy-har**
Closes #5689

### CODE REVIEW

**Review by ortz — APPROVED** [review]
LGTM

**Comment by arielshaqed** [comment]
This PR *really* needs to link to an issue. It is of intense interest to users, and it retreats on a documented [commitment](https://docs.lakefs.io/reference/access-control-lists.html#scopes)  that we made to our users.

**Comment by arielshaqed** [comment]
I've also mentioned it [on Slack](https://lakefs.slack.com/archives/C016726JLJW/p1677750496072379?thread_ts=1677750496.072379&cid=C016726JLJW), link is just for one instance.

So we need to state the requirement explicitly and explain why it changes, at the product level.

**Comment by ortz** [comment]
> This PR _really_ needs to link to an issue. It is of intense interest to users, and it retreats on a documented [commitment](https://docs.lakefs.io/reference/access-control-lists.html#scopes) that we made to our users.

You're absolutely right, I've created an [issue to represent this feature change request](https://github.com/treeverse/lakeFS/issues/5689).

**Review by arielshaqed — APPROVED** [review]
Thanks!

But note that we cannot pull this before we have an updated upgrade script.  Otherwise someone who's already installed and updated to ACLs-with-repositories may be surprised!

**Pull request merged**
